import { Schema, model } from 'mongoose';

export const EMPLOYEE_TYPES=['PERMANENT','TEMPORARY','CONTRACT','INTERN','CONSULTANT','PART_TIME','FREELANCE'] as const;
export const EMPLOYEE_STATUSES=['ACTIVE','INACTIVE','ON_PROBATION','ON_NOTICE','SUSPENDED','RESIGNED','TERMINATED','RETIRED'] as const;
export type EmployeeType=typeof EMPLOYEE_TYPES[number]; export type EmployeeStatus=typeof EMPLOYEE_STATUSES[number];
type Address={line1?:string;line2?:string;city?:string;state?:string;postalCode?:string;country?:string};
type History={type:string;from?:string;to?:string;note?:string;effectiveDate:Date;changedBy?:string};
export interface IEmployee { employeeId:string; profilePhoto?:string; firstName:string;middleName?:string;lastName:string;gender?:string;dateOfBirth?:Date;bloodGroup?:string;maritalStatus?:string;nationality?:string;personalEmail?:string;personalPhone?:string;emergencyContact?:{name?:string;relationship?:string;phone?:string};currentAddress?:Address;permanentAddress?:Address;email:string;workPhone?:string;employeeType:EmployeeType;status:EmployeeStatus;department:string;designation:string;reportingManager?:string;teamLeader?:string;branch?:string;location?:string;joiningDate:Date;probationEndDate?:Date;confirmationDate?:Date;noticePeriod?:string;contractStartDate?:Date;contractEndDate?:Date;workMode?:string;shift?:string;weeklyOff?:string[];bank?:{accountHolderName?:string;bankName?:string;accountNumberEncrypted?:string;routingCodeEncrypted?:string;branch?:string;accountType?:string};statutory?:Array<{country:string;type:string;valueEncrypted:string}>;history?:History[];organizationId?:string;deletedAt?:Date|null }
const address={line1:String,line2:String,city:String,state:String,postalCode:String,country:String};
const schema=new Schema<IEmployee>({employeeId:{type:String,required:true,unique:true,index:true},profilePhoto:String,firstName:{type:String,required:true,trim:true},middleName:String,lastName:{type:String,required:true,trim:true},gender:String,dateOfBirth:Date,bloodGroup:String,maritalStatus:String,nationality:String,personalEmail:String,personalPhone:String,emergencyContact:{name:String,relationship:String,phone:String},currentAddress:address,permanentAddress:address,email:{type:String,required:true,lowercase:true,trim:true},workPhone:String,employeeType:{type:String,enum:EMPLOYEE_TYPES,default:'PERMANENT'},status:{type:String,enum:EMPLOYEE_STATUSES,default:'ACTIVE',index:true},department:{type:String,required:true,index:true},designation:{type:String,required:true},reportingManager:String,teamLeader:String,branch:String,location:{type:String,index:true},joiningDate:{type:Date,required:true},probationEndDate:Date,confirmationDate:Date,noticePeriod:String,contractStartDate:Date,contractEndDate:Date,workMode:String,shift:String,weeklyOff:[String],bank:{accountHolderName:String,bankName:String,accountNumberEncrypted:{type:String,select:false},routingCodeEncrypted:{type:String,select:false},branch:String,accountType:String},statutory:[{country:String,type:String,valueEncrypted:{type:String,select:false}}],history:[{type:{type:String,required:true},from:String,to:String,note:String,effectiveDate:{type:Date,default:Date.now},changedBy:String}],organizationId:{type:String,index:true},deletedAt:{type:Date,default:null}},{timestamps:true});
schema.index({organizationId:1,employeeId:1},{unique:true}); schema.index({organizationId:1,email:1},{unique:true});
export const Employee=model<IEmployee>('Employee',schema);
