export type DemoRequestEmailData = {
  requestId: string; fullName: string; workEmail: string; phoneCountryCode: string; phoneNumber: string;
  jobTitle: string; companyName: string; industry: string; companySize: string; city?: string; state?: string;
  country: string; interestedModules: string[]; currentHRMethod: string; preferredDemoDate: string;
  preferredDemoTime: string; preferredTimezone: string; preferredContactMethod: string;
  additionalRequirements?: string; detailUrl: string;
};
export type RenderedDemoEmail = { subject: string; text: string; html: string };
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));
const row = (label:string,value:string) => `<tr><td style="padding:7px 0;color:#64748b;font-size:13px;vertical-align:top;width:42%">${escapeHtml(label)}</td><td style="padding:7px 0;color:#0f172a;font-size:14px;font-weight:600;vertical-align:top">${escapeHtml(value)}</td></tr>`;
const layout = (eyebrow:string,title:string,intro:string,content:string,footer:string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a"><div style="display:none;max-height:0;overflow:hidden;color:transparent">${escapeHtml(intro)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f5f9"><tr><td align="center" style="padding:36px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border:1px solid #e2e8f0;border-radius:20px;overflow:hidden"><tr><td style="background:#312e81;padding:28px 34px"><div style="font-size:20px;font-weight:800;color:#fff">EmployeeHub</div><div style="margin-top:4px;font-size:12px;color:#c7d2fe">Employee Management System</div></td></tr><tr><td style="padding:34px"><div style="font-size:11px;line-height:16px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;color:#4f46e5">${escapeHtml(eyebrow)}</div><h1 style="margin:10px 0 12px;font-size:28px;line-height:35px;color:#0f172a">${escapeHtml(title)}</h1><p style="margin:0 0 26px;font-size:15px;line-height:24px;color:#475569">${escapeHtml(intro)}</p>${content}</td></tr><tr><td style="border-top:1px solid #e2e8f0;padding:22px 34px;font-size:12px;line-height:19px;color:#64748b">${escapeHtml(footer)}</td></tr></table></td></tr></table></body></html>`;

export function renderCustomerDemoConfirmation(data:DemoRequestEmailData):RenderedDemoEmail {
  const subject=`We received your EmployeeHub demo request · ${data.requestId}`;
  const content=`<div style="border:1px solid #e2e8f0;border-radius:14px;padding:16px 20px;background:#f8fafc"><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${row('Request ID',data.requestId)}${row('Company',data.companyName)}${row('Preferred date',data.preferredDemoDate)}${row('Preferred time',`${data.preferredDemoTime} (${data.preferredTimezone})`)}${row('Contact method',data.preferredContactMethod)}</table></div><div style="margin-top:24px"><div style="font-size:13px;font-weight:800;color:#334155">Modules you are interested in</div><p style="margin:7px 0 0;font-size:14px;line-height:22px;color:#475569">${data.interestedModules.map(escapeHtml).join(' &nbsp;·&nbsp; ')}</p></div><div style="margin-top:24px;border-left:4px solid #818cf8;padding:2px 0 2px 16px"><div style="font-size:14px;font-weight:800;color:#1e293b">What happens next?</div><p style="margin:6px 0 0;font-size:14px;line-height:22px;color:#475569">A product specialist will review your requirements and contact you to confirm the schedule and meeting details.</p></div>`;
  return{subject,text:`Hello ${data.fullName},\n\nWe received your EmployeeHub demo request.\nRequest ID: ${data.requestId}\nCompany: ${data.companyName}\nPreferred date: ${data.preferredDemoDate}\nPreferred time: ${data.preferredDemoTime} (${data.preferredTimezone})\nContact method: ${data.preferredContactMethod}\nModules: ${data.interestedModules.join(', ')}\n\nA product specialist will contact you to confirm the schedule.`,html:layout('Demo request received',`Thanks, ${data.fullName}`,'Your personalized EmployeeHub demo request is safely in our queue.',content,'You received this operational email because a demo was requested using your work email. This is not a marketing subscription.')};
}

export function renderSuperAdminNewDemoRequest(data:DemoRequestEmailData):RenderedDemoEmail {
  const subject=`New demo request · ${data.companyName} · ${data.requestId}`,location=[data.city,data.state,data.country].filter(Boolean).join(', ');
  const content=`<div style="border-radius:14px;background:#eef2ff;padding:16px 20px"><div style="font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:#4338ca">Lead summary</div><div style="margin-top:7px;font-size:20px;font-weight:800;color:#1e1b4b">${escapeHtml(data.companyName)}</div><div style="margin-top:4px;font-size:13px;color:#4f46e5">${escapeHtml(data.requestId)}</div></div><div style="margin-top:22px"><div style="font-size:13px;font-weight:800;color:#334155">Contact and company</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:6px">${row('Contact',`${data.fullName} · ${data.jobTitle}`)}${row('Work email',data.workEmail)}${row('Phone',`${data.phoneCountryCode} ${data.phoneNumber}`)}${row('Company profile',`${data.industry} · ${data.companySize}`)}${row('Location',location)}</table></div><div style="margin-top:22px"><div style="font-size:13px;font-weight:800;color:#334155">Demo requirements</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:6px">${row('Modules',data.interestedModules.join(', '))}${row('Current HR method',data.currentHRMethod)}${row('Preferred slot',`${data.preferredDemoDate}, ${data.preferredDemoTime} (${data.preferredTimezone})`)}${row('Contact method',data.preferredContactMethod)}${row('Additional notes',data.additionalRequirements||'None provided')}</table></div><div style="margin-top:26px"><a href="${escapeHtml(data.detailUrl)}" style="display:inline-block;border-radius:10px;background:#4f46e5;padding:13px 20px;color:#fff;font-size:14px;font-weight:800;text-decoration:none">Open demo request</a></div>`;
  return{subject,text:`New demo request ${data.requestId}\n${data.fullName} (${data.workEmail}) from ${data.companyName}\nPreferred: ${data.preferredDemoDate}, ${data.preferredDemoTime} (${data.preferredTimezone})\nModules: ${data.interestedModules.join(', ')}\nOpen: ${data.detailUrl}`,html:layout('Super Admin notification','A new demo request is ready','Review the lead details and assign the next follow-up action.',content,'This internal notification contains lead information. Handle it according to your organization’s privacy and access policies.')};
}

export const demoEmailPreviewSample:DemoRequestEmailData=Object.freeze({requestId:'DEMO-2026-0042',fullName:'Aarav Patel',workEmail:'aarav.patel@example.test',phoneCountryCode:'+91',phoneNumber:'98765 43210',jobTitle:'People Operations Lead',companyName:'Northstar Labs',industry:'Software & Technology',companySize:'201–500 employees',city:'Bengaluru',state:'Karnataka',country:'India',interestedModules:['Attendance','Leave Management','Payroll'],currentHRMethod:'Spreadsheets and separate payroll software',preferredDemoDate:'24 July 2026',preferredDemoTime:'11:30 AM',preferredTimezone:'Asia/Kolkata',preferredContactMethod:'Google Meet',additionalRequirements:'Interested in multi-location attendance and payroll approval workflows.',detailUrl:'https://example.test/super-admin/demo-requests/sample-preview'});
