import type {Types} from 'mongoose'; import {AccessModule,AccessPermission,AccessRole,MenuConfiguration,PermissionAction,RolePermission,UserRole} from './access-control.models.js';
const moduleRows=[['Dashboard','DASHBOARD','dashboard','/'],['Employees','EMPLOYEES','employee','/employees'],['Departments','DEPARTMENTS','department','/masters'],['Designations','DESIGNATIONS','designation','/masters'],['Attendance','ATTENDANCE','attendance','/attendance'],['Shifts','SHIFTS','shift','/shifts'],['Leave','LEAVE','leave','/leaves'],['Payroll','PAYROLL','payroll','/payroll'],['Recruitment','RECRUITMENT','recruitment','/recruitment'],['Performance','PERFORMANCE','performance','/performance'],['Documents','DOCUMENTS','document','/documents'],['Assets','ASSETS','asset','/assets'],['Expenses','EXPENSES','expense','#'],['Reports','REPORTS','report','/reports'],['Audit Logs','AUDIT_LOGS','audit','/audit-logs'],['Roles and Permissions','ACCESS_CONTROL','access_control','/roles'],['Dynamic Modules','DYNAMIC_MODULES','module','/modules'],['Settings','SETTINGS','settings','/settings/security']] as const;
const actionRows=['VIEW','CREATE','UPDATE','DELETE','RESTORE','APPROVE','REJECT','ASSIGN','UNASSIGN','IMPORT','EXPORT','DOWNLOAD','UPLOAD','MANAGE','VIEW_SENSITIVE','GENERATE','PUBLISH'];
const roleRows=[['Super Admin','SUPER_ADMIN',1000,'ALL'],['Organization Admin','ORGANIZATION_ADMIN',900,'ORGANIZATION'],['HR Admin','HR_ADMIN',700,'ORGANIZATION'],['HR Executive','HR_EXECUTIVE',600,'ORGANIZATION'],['Department Manager','DEPARTMENT_MANAGER',500,'DEPARTMENT'],['Team Leader','TEAM_LEADER',400,'TEAM'],['Payroll Manager','PAYROLL_MANAGER',650,'ORGANIZATION'],['Recruiter','RECRUITER',550,'ORGANIZATION'],['Finance User','FINANCE_USER',450,'ORGANIZATION'],['Employee','EMPLOYEE',100,'OWN']] as const;
export async function seedAccessControl(actorId:Types.ObjectId,userId?:Types.ObjectId){
 const actions=new Map<string,any>();for(const [i,code] of actionRows.entries()){const row=await PermissionAction.findOneAndUpdate({code},{$setOnInsert:{name:code.replaceAll('_',' '),code,displayOrder:i,riskLevel:['DELETE','APPROVE','MANAGE','VIEW_SENSITIVE'].includes(code)?'HIGH':'LOW',isSystemAction:true,status:'ACTIVE',isDeleted:false,createdBy:actorId}},{upsert:true,new:true});actions.set(code,row)}
 const modules=[];for(const [i,[name,code,slug,route]] of moduleRows.entries()){modules.push(await AccessModule.findOneAndUpdate({organizationId:null,code},{$setOnInsert:{organizationId:null,name,code,slug,route,displayOrder:i,isMenuVisible:true,isPermissionEnabled:true,isSystemModule:true,status:'ACTIVE',isDeleted:false,createdBy:actorId}},{upsert:true,new:true}))}
 const permissions=[];for(const mod of modules){for(const code of ['VIEW','CREATE','UPDATE','DELETE']){const action=actions.get(code);const permissionCode=`${mod.slug}.${code.toLowerCase()}`;permissions.push(await AccessPermission.findOneAndUpdate({organizationId:null,code:permissionCode},{$setOnInsert:{organizationId:null,moduleId:mod._id,actionId:action._id,name:`${mod.name} ${action.name}`,code:permissionCode,riskLevel:action.riskLevel,isSensitive:false,isSystemPermission:true,allowedScopes:['OWN','TEAM','DEPARTMENT','BRANCH','ORGANIZATION','ALL'],status:'ACTIVE',isDeleted:false,createdBy:actorId}},{upsert:true,new:true}))}}
 const special=[['module','RESTORE'],['module','GENERATE'],['role','RESTORE'],['role','ASSIGN'],['access_control','MANAGE']] as const;for(const [slug,code] of special){const mod=modules.find(x=>x.slug===slug),action=actions.get(code);if(mod&&action){const permissionCode=`${slug}.${code.toLowerCase()}`;permissions.push(await AccessPermission.findOneAndUpdate({organizationId:null,code:permissionCode},{$setOnInsert:{organizationId:null,moduleId:mod._id,actionId:action._id,name:`${mod.name} ${action.name}`,code:permissionCode,riskLevel:action.riskLevel,isSystemPermission:true,allowedScopes:['ORGANIZATION','ALL'],status:'ACTIVE',isDeleted:false,createdBy:actorId}},{upsert:true,new:true}))}}
 const roles=new Map<string,any>();for(const [name,code,priority,defaultScope] of roleRows){roles.set(code,await AccessRole.findOneAndUpdate({organizationId:null,code},{$setOnInsert:{organizationId:null,name,code,type:'SYSTEM',priority,defaultScope,isSystemRole:true,isDefaultRole:code==='EMPLOYEE',status:'ACTIVE',isDeleted:false,createdBy:actorId}},{upsert:true,new:true}))}
 const superRole=roles.get('SUPER_ADMIN');for(const permission of permissions)await RolePermission.updateOne({organizationId:null,roleId:superRole._id,permissionId:permission._id},{$setOnInsert:{organizationId:null,roleId:superRole._id,permissionId:permission._id,effect:'ALLOW',scope:'ALL',createdBy:actorId}},{upsert:true});
 for(const mod of modules)await MenuConfiguration.findOneAndUpdate({organizationId:null,moduleId:mod._id},{$setOnInsert:{organizationId:null,moduleId:mod._id,name:mod.name,route:mod.route||'#',displayOrder:mod.displayOrder,status:'ACTIVE',requiredPermission:`${mod.slug}.view`}},{upsert:true});
 if(userId)await UserRole.updateOne({organizationId:actorId,userId,roleId:superRole._id,status:'ACTIVE'},{$setOnInsert:{organizationId:actorId,userId,roleId:superRole._id,isPrimary:true,scope:'ALL',effectiveFrom:new Date(),assignmentType:'PERMANENT',reason:'System bootstrap',assignedBy:actorId,status:'ACTIVE'}},{upsert:true});
 return{modules:modules.length,actions:actions.size,permissions:permissions.length,roles:roles.size,menus:modules.length};
}
