import { z } from 'zod'; import { EFFECTS,RISKS,SCOPES,STATUSES } from './access-control.constants.js';
const id=z.string().regex(/^[a-f\d]{24}$/i), scope=z.enum(SCOPES), effect=z.enum(EFFECTS), status=z.enum(STATUSES);
export const moduleCreate=z.object({body:z.object({name:z.string().min(1),code:z.string().regex(/^[A-Z][A-Z0-9_]*$/),slug:z.string().min(1),description:z.string().optional(),icon:z.string().optional(),route:z.string().optional(),parentModuleId:id.nullish(),displayOrder:z.number().int().default(0),isMenuVisible:z.boolean().default(true),isPermissionEnabled:z.boolean().default(true),isSystemModule:z.boolean().default(false),status:status.default('ACTIVE'),metadata:z.record(z.string(),z.unknown()).optional()})});
export const actionCreate=z.object({body:z.object({name:z.string().min(1),code:z.string().regex(/^[A-Z][A-Z0-9_]*$/),description:z.string().optional(),displayOrder:z.number().int().default(0),riskLevel:z.enum(RISKS).default('LOW'),isSystemAction:z.boolean().default(false),status:status.default('ACTIVE')})});
export const permissionCreate=z.object({body:z.object({moduleId:id,submoduleId:id.nullish(),actionId:id,name:z.string().min(1),description:z.string().optional(),riskLevel:z.enum(RISKS).default('LOW'),isSensitive:z.boolean().default(false),isSystemPermission:z.boolean().default(false),allowedScopes:z.array(scope).min(1),status:status.default('ACTIVE')})});
export const roleCreate=z.object({body:z.object({name:z.string().min(1),code:z.string().regex(/^[A-Z][A-Z0-9_]*$/),description:z.string().optional(),type:z.enum(['SYSTEM','CUSTOM']).default('CUSTOM'),priority:z.number().int().default(0),defaultScope:scope.default('OWN'),isSystemRole:z.boolean().default(false),isDefaultRole:z.boolean().default(false),status:status.default('ACTIVE')})});
export const rolePermissions=z.object({body:z.object({permissions:z.array(z.object({permissionId:id,effect,scope,conditions:z.record(z.string(),z.unknown()).optional()})),reason:z.string().min(1)})});
export const userRoleCreate=z.object({body:z.object({roleId:id,isPrimary:z.boolean().default(false),scope,effectiveFrom:z.coerce.date(),effectiveUntil:z.coerce.date().nullish(),assignmentType:z.enum(['PERMANENT','TEMPORARY']),scopeReferences:z.record(z.string(),z.array(id)).optional(),reason:z.string().min(1)}).superRefine((v,c)=>{if(v.assignmentType==='TEMPORARY'&&!v.effectiveUntil)c.addIssue({code:'custom',path:['effectiveUntil'],message:'Temporary roles require an expiry date'})})});
export const overrideCreate=z.object({body:z.object({permissionId:id,effect,scope,effectiveFrom:z.coerce.date(),effectiveUntil:z.coerce.date().nullish(),conditions:z.record(z.string(),z.unknown()).optional(),reason:z.string().min(1)})});

