import crypto from 'node:crypto'; import bcrypt from 'bcryptjs'; import jwt,{type SignOptions} from 'jsonwebtoken'; import { env } from '../../config/environment.js'; import { AppError } from '../../utils/AppError.js'; import { decrypt,encrypt,hashToken,newMfaSecret,randomToken,verifyTotp } from '../../utils/security.js'; import { User } from '../../models/User.js'; import { Session } from '../../models/Session.js'; import { AuthToken,type AuthTokenPurpose } from '../../models/AuthToken.js'; import { LoginActivity } from '../../models/LoginActivity.js'; import { EmailService } from '../../services/email.service.js';
export type RequestMeta={ipAddress:string;userAgent:string;deviceName:string;deviceId?:string}; const emailService=new EmailService(); const MAX_ATTEMPTS=5; const LOCK_MS=15*60*1000;
const accessToken=(user:{id:string;role:string;organizationId?:string})=>jwt.sign({role:user.role,organizationId:user.organizationId},env.JWT_ACCESS_SECRET,{expiresIn:env.JWT_ACCESS_EXPIRES_IN as SignOptions['expiresIn'],subject:user.id});
export class AuthService{
 async login(email:string,password:string,rememberMe:boolean,mfaCode:string|undefined,meta:RequestMeta){const user=await User.findOne({email}).select('+password +failedLoginAttempts +lockUntil +mfaSecret');if(!user||!user.active){await this.activity(undefined,email,false,'INVALID_CREDENTIALS',meta);throw new AppError(401,'Invalid email or password','INVALID_CREDENTIALS')}if(user.lockUntil&&user.lockUntil>new Date()){await this.activity(user.id,email,false,'ACCOUNT_LOCKED',meta);throw new AppError(423,'Account temporarily locked. Try again later.','ACCOUNT_LOCKED')}if(!(await bcrypt.compare(password,user.password))){user.failedLoginAttempts=(user.failedLoginAttempts||0)+1;if(user.failedLoginAttempts>=MAX_ATTEMPTS){user.lockUntil=new Date(Date.now()+LOCK_MS);user.failedLoginAttempts=0}await user.save();await this.activity(user.id,email,false,'INVALID_CREDENTIALS',meta);throw new AppError(401,'Invalid email or password','INVALID_CREDENTIALS')}if(user.mfaEnabled){if(!mfaCode)throw new AppError(428,'Multi-factor authentication code required','MFA_REQUIRED');if(!user.mfaSecret||!verifyTotp(decrypt(user.mfaSecret),mfaCode)){await this.activity(user.id,email,false,'INVALID_MFA',meta);throw new AppError(401,'Invalid authentication code','INVALID_MFA')}}user.failedLoginAttempts=0;user.lockUntil=undefined;await user.save();const tokens=await this.createSession(user,rememberMe,meta);await this.activity(user.id,email,true,undefined,meta);return{...tokens,user:{id:user.id,name:user.name,email:user.email,role:user.role,emailVerified:user.emailVerified,mfaEnabled:user.mfaEnabled}}}
 async createSession(user:{id:string;role:string;organizationId?:string},rememberMe:boolean,meta:RequestMeta){const days=rememberMe?7:1;const session=await Session.create({userId:user.id,refreshTokenHash:'pending',deviceId:meta.deviceId||crypto.randomUUID(),deviceName:meta.deviceName,ipAddress:meta.ipAddress,userAgent:meta.userAgent,rememberMe,lastActiveAt:new Date(),expiresAt:new Date(Date.now()+days*86400000)});const refreshToken=jwt.sign({sid:session.id},env.JWT_REFRESH_SECRET,{expiresIn:(rememberMe?env.JWT_REFRESH_EXPIRES_IN:'1d') as SignOptions['expiresIn'],subject:user.id});session.refreshTokenHash=hashToken(refreshToken);await session.save();return{token:accessToken(user),refreshToken}}
 async refresh(token:string,meta:RequestMeta){let payload:{sub?:string;sid?:string};try{payload=jwt.verify(token,env.JWT_REFRESH_SECRET) as typeof payload}catch{throw new AppError(401,'Invalid or expired refresh token','INVALID_REFRESH_TOKEN')}const session=await Session.findById(payload.sid);if(!session||session.revokedAt||session.expiresAt<new Date()||session.refreshTokenHash!==hashToken(token))throw new AppError(401,'Session expired','SESSION_EXPIRED');const user=await User.findById(payload.sub);if(!user||!user.active)throw new AppError(401,'Account unavailable','UNAUTHORIZED');session.lastActiveAt=new Date();session.ipAddress=meta.ipAddress;await session.save();return{token:accessToken(user)}}
 async logout(userId:string,refreshToken?:string){if(refreshToken)await Session.updateOne({userId,refreshTokenHash:hashToken(refreshToken)},{$set:{revokedAt:new Date()}})}
 async logoutAll(userId:string){await Session.updateMany({userId,revokedAt:{$exists:false}},{$set:{revokedAt:new Date()}})}
 async issuePurposeToken(email:string,purpose:AuthTokenPurpose){const user=await User.findOne({email});if(!user)return;const token=purpose==='PASSWORD_RESET'?String(crypto.randomInt(100000,1000000)):randomToken();await AuthToken.deleteMany({userId:user.id,purpose});await AuthToken.create({userId:user.id,tokenHash:hashToken(token),purpose,expiresAt:new Date(Date.now()+(purpose==='PASSWORD_RESET'?600000:86400000))});const message=purpose==='PASSWORD_RESET'?`Your EmployeeHub password reset code is ${token}. It expires in 10 minutes.`:`${env.CLIENT_URL}/verify-email?token=${token}`;await emailService.send(user.email,purpose==='PASSWORD_RESET'?'EmployeeHub password reset code':'Verify your EmployeeHub email',message)}
 async verifyResetCode(email:string,code:string){const user=await User.findOne({email});if(!user)throw new AppError(400,'Code is invalid or expired','INVALID_OTP');const record=await AuthToken.findOne({userId:user.id,tokenHash:hashToken(code),purpose:'PASSWORD_RESET',usedAt:{$exists:false},expiresAt:{$gt:new Date()}});if(!record)throw new AppError(400,'Code is invalid or expired','INVALID_OTP');return{resetToken:code}}
 async consumeToken(token:string,purpose:AuthTokenPurpose){const record=await AuthToken.findOne({tokenHash:hashToken(token),purpose,usedAt:{$exists:false},expiresAt:{$gt:new Date()}});if(!record)throw new AppError(400,'Token is invalid or expired','INVALID_TOKEN');record.usedAt=new Date();await record.save();return record}
 async resetPassword(token:string,password:string){const record=await this.consumeToken(token,'PASSWORD_RESET');await User.updateOne({_id:record.userId},{$set:{password:await bcrypt.hash(password,12),passwordChangedAt:new Date(),failedLoginAttempts:0},$unset:{lockUntil:1}});await Session.updateMany({userId:record.userId,revokedAt:{$exists:false}},{$set:{revokedAt:new Date()}})}
 async verifyEmail(token:string){const record=await this.consumeToken(token,'EMAIL_VERIFICATION');await User.updateOne({_id:record.userId},{$set:{emailVerified:true}})}
 async changePassword(userId:string,current:string,next:string){const user=await User.findById(userId).select('+password');if(!user||!(await bcrypt.compare(current,user.password)))throw new AppError(400,'Current password is incorrect','INVALID_PASSWORD');user.password=await bcrypt.hash(next,12);user.passwordChangedAt=new Date();await user.save();await Session.updateMany({userId,revokedAt:{$exists:false}},{$set:{revokedAt:new Date()}})}
 async setupMfa(userId:string){const secret=newMfaSecret();await User.updateOne({_id:userId},{$set:{mfaSecret:encrypt(secret),mfaEnabled:false}});return{secret,otpauthUrl:`otpauth://totp/EmployeeHub:${userId}?secret=${secret}&issuer=EmployeeHub`}}
 async enableMfa(userId:string,code:string){const user=await User.findById(userId).select('+mfaSecret');if(!user?.mfaSecret||!verifyTotp(decrypt(user.mfaSecret),code))throw new AppError(400,'Invalid authentication code','INVALID_MFA');user.mfaEnabled=true;await user.save()}
 async disableMfa(userId:string,code:string){const user=await User.findById(userId).select('+mfaSecret');if(!user?.mfaSecret||!verifyTotp(decrypt(user.mfaSecret),code))throw new AppError(400,'Invalid authentication code','INVALID_MFA');user.mfaEnabled=false;user.mfaSecret=undefined;await user.save()}
 sessions(userId:string){return Session.find({userId,revokedAt:{$exists:false},expiresAt:{$gt:new Date()}}).select('-refreshTokenHash').sort({lastActiveAt:-1}).lean()}
 activityList(userId:string){return LoginActivity.find({userId}).sort({createdAt:-1}).limit(50).lean()}
 revokeSession(userId:string,id:string){return Session.updateOne({_id:id,userId},{$set:{revokedAt:new Date()}})}
 private activity(userId:string|undefined,email:string,success:boolean,reason:string|undefined,meta:RequestMeta){return LoginActivity.create({userId,email,success,reason,...meta})}
}
