export type Scope='OWN'|'TEAM'|'DEPARTMENT'|'BRANCH'|'ORGANIZATION'|'ALL';
export type Effect='ALLOW'|'DENY';
export type AccessRole={_id:string;name:string;code:string;description?:string;type:'SYSTEM'|'CUSTOM';status:string;priority:number;defaultScope:Scope;isDefaultRole?:boolean;isSystemRole?:boolean};
export type AccessPermission={_id:string;name:string;code:string;moduleId:string;actionId:string;riskLevel:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';isSensitive:boolean;allowedScopes:Scope[]};
export type RolePermission={permissionId:AccessPermission|string;effect:Effect;scope:Scope;conditions?:Record<string,unknown>};
export type AccessModule={_id:string;name:string;code:string;slug:string;description?:string;icon?:string;route?:string;parentModuleId?:string|null;displayOrder:number;isMenuVisible:boolean;isPermissionEnabled:boolean;isSystemModule:boolean;status:'ACTIVE'|'INACTIVE';isDeleted:boolean;children?:AccessModule[]};
export type PermissionAction={_id:string;name:string;code:string;riskLevel:string;status:string};
export type MenuConfiguration={_id:string;moduleId:string;name:string;route:string;icon?:string;requiredPermission?:string;parentMenuId?:string|null;displayOrder:number;status:string};
type Envelope<T>={success:boolean;message:string;data:T;pagination?:{page:number;limit:number;totalRecords:number;totalPages:number};errors?:unknown};
const base=import.meta.env.VITE_API_URL||'/api/v1';
const token=()=>localStorage.getItem('token')||sessionStorage.getItem('token')||'';
async function refreshAccessToken(){const target=localStorage.getItem('refreshToken')?localStorage:sessionStorage,refreshToken=target.getItem('refreshToken');if(!refreshToken)return false;const response=await fetch(`${base}/auth/refresh`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refreshToken})});if(!response.ok){localStorage.clear();sessionStorage.clear();window.location.assign('/login');return false}const payload=await response.json() as Envelope<{token:string}>;target.setItem('token',payload.data.token);return true}
async function request<T>(path:string,init:RequestInit={},retried=false):Promise<Envelope<T>>{const response=await fetch(`${base}${path}`,{...init,headers:{authorization:`Bearer ${token()}`,'content-type':'application/json',...init.headers}});if(response.status===401&&!retried&&await refreshAccessToken())return request<T>(path,init,true);const payload=await response.json().catch(()=>({message:response.statusText}));if(!response.ok)throw new Error(payload.message||'Request failed');return payload as Envelope<T>}
const body=(value:unknown)=>JSON.stringify(value);
export const accessControlApi={
 modules:(includeDeleted=false)=>request<AccessModule[]>(`/modules?limit=100${includeDeleted?'&includeDeleted=true':''}`),moduleTree:()=>request<AccessModule[]>('/modules/tree'),createModule:(value:Partial<AccessModule>)=>request<AccessModule>('/modules',{method:'POST',body:body(value)}),updateModule:(id:string,value:Partial<AccessModule>)=>request<AccessModule>(`/modules/${id}`,{method:'PUT',body:body(value)}),setModuleStatus:(id:string,status:'ACTIVE'|'INACTIVE')=>request<AccessModule>(`/modules/${id}/status`,{method:'PATCH',body:body({status})}),deleteModule:(id:string)=>request(`/modules/${id}`,{method:'DELETE'}),restoreModule:(id:string)=>request(`/modules/${id}/restore`,{method:'POST'}),reorderModules:(items:{moduleId:string;displayOrder:number}[])=>request('/modules/reorder',{method:'PATCH',body:body({items})}),generatePermissions:(id:string,actionCodes:string[])=>request<{created:number;skipped:number}>(`/modules/${id}/generate-permissions`,{method:'POST',body:body({actionCodes})}),
 permissionActions:()=>request<PermissionAction[]>('/permission-actions?limit=100'),
 menus:()=>request<MenuConfiguration[]>('/menu-configurations?limit=100'),createMenu:(value:Partial<MenuConfiguration>)=>request<MenuConfiguration>('/menu-configurations',{method:'POST',body:body(value)}),updateMenu:(id:string,value:Partial<MenuConfiguration>)=>request<MenuConfiguration>(`/menu-configurations/${id}`,{method:'PUT',body:body(value)}),deleteMenu:(id:string)=>request(`/menu-configurations/${id}`,{method:'DELETE'}),
 roles:()=>request<AccessRole[]>('/roles?limit=100'), createRole:(value:Partial<AccessRole>)=>request<AccessRole>('/roles',{method:'POST',body:body(value)}), updateRole:(id:string,value:Partial<AccessRole>)=>request<AccessRole>(`/roles/${id}`,{method:'PUT',body:body(value)}), deleteRole:(id:string)=>request(`/roles/${id}`,{method:'DELETE'}), duplicateRole:(id:string,name:string,code:string)=>request<AccessRole>(`/roles/${id}/duplicate`,{method:'POST',body:body({name,code})}),
 permissions:()=>request<AccessPermission[]>('/permissions?limit=100'), rolePermissions:(id:string)=>request<RolePermission[]>(`/roles/${id}/permissions`), replaceRolePermissions:(id:string,permissions:{permissionId:string;effect:Effect;scope:Scope;conditions?:Record<string,unknown>}[],reason:string)=>request(`/roles/${id}/permissions`,{method:'PUT',body:body({permissions,reason})}),
 assignRole:(userId:string,value:{roleId:string;isPrimary:boolean;scope:Scope;effectiveFrom:string;effectiveUntil?:string;assignmentType:'PERMANENT'|'TEMPORARY';reason:string})=>request(`/users/${userId}/roles`,{method:'POST',body:body(value)}),
 createOverride:(userId:string,value:{permissionId:string;effect:Effect;scope:Scope;effectiveFrom:string;effectiveUntil?:string;reason:string})=>request(`/users/${userId}/permission-overrides`,{method:'POST',body:body(value)}),
 effectivePermissions:(userId?:string)=>request(userId?`/users/${userId}/effective-permissions`:'/auth/me/permissions'), menu:()=>request<MenuConfiguration[]>('/auth/me/menu'), refresh:(userId:string)=>request(`/users/${userId}/permissions/refresh`,{method:'POST'})
};
