import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'; import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query'; import type { RootState } from '../store'; import type { Employee, User } from '../types';
type Envelope<T> = { success: boolean; message: string; data: T }; type EmployeePage = { items: Employee[]; pagination: { page: number; limit: number; total: number; pages: number } };
export type Session = { _id: string; deviceId: string; deviceName: string; ipAddress: string; userAgent: string; lastActiveAt: string; expiresAt: string }; export type Activity = { _id: string; success: boolean; reason?: string; ipAddress: string; deviceName: string; createdAt: string };
const rawBaseQuery = fetchBaseQuery({ baseUrl: import.meta.env.VITE_API_BASE_URL || '/api/v1', prepareHeaders: (headers, { getState }) => { const token = (getState() as RootState).auth.token; if (token) headers.set('authorization', `Bearer ${token}`); headers.set('x-device-name', navigator.userAgent); return headers } });
const baseQueryWithRefresh: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError> = async (args, ctx, options) => { let result = await rawBaseQuery(args, ctx, options); const url = typeof args === 'string' ? args : args.url; if (result.error?.status === 401 && !url.includes('/auth/login') && !url.includes('/auth/refresh')) { const refreshToken = (ctx.getState() as RootState).auth.refreshToken; if (refreshToken) { const refreshed = await rawBaseQuery({ url: '/auth/refresh', method: 'POST', body: { refreshToken } }, ctx, options) as { data?: Envelope<{ token: string }> }; if (refreshed.data?.data.token) { ctx.dispatch({ type: 'auth/tokenRefreshed', payload: refreshed.data.data.token }); result = await rawBaseQuery(args, ctx, options) } else ctx.dispatch({ type: 'auth/signedOut' }) } else ctx.dispatch({ type: 'auth/signedOut' }) } return result };
export const api = createApi({
    reducerPath: 'api', baseQuery: baseQueryWithRefresh, tagTypes: ['Employees', 'Sessions'], endpoints: builder => ({
        login: builder.mutation<Envelope<{ token: string; refreshToken: string; user: User }>, { email: string; password: string; rememberMe: boolean; mfaCode?: string; deviceId?: string }>({ query: body => ({ url: '/auth/login', method: 'POST', body }) }), refresh: builder.mutation<Envelope<{ token: string }>, { refreshToken: string }>({ query: body => ({ url: '/auth/refresh', method: 'POST', body }) }), logout: builder.mutation<Envelope<null>, { refreshToken: string | null }>({ query: body => ({ url: '/auth/logout', method: 'POST', body }) }), forgotPassword: builder.mutation<Envelope<null>, { email: string }>({ query: body => ({ url: '/auth/forgot-password', method: 'POST', body }) }), resetPassword: builder.mutation<Envelope<null>, { token: string; password: string }>({ query: body => ({ url: '/auth/reset-password', method: 'POST', body }) }), verifyEmail: builder.mutation<Envelope<null>, { token: string }>({ query: body => ({ url: '/auth/verify-email', method: 'POST', body }) }), changePassword: builder.mutation<Envelope<null>, { currentPassword: string; newPassword: string }>({ query: body => ({ url: '/auth/change-password', method: 'POST', body }) }), sessions: builder.query<Envelope<Session[]>, void>({ query: () => '/auth/sessions', providesTags: ['Sessions'] }), revokeSession: builder.mutation<Envelope<null>, string>({ query: id => ({ url: `/auth/sessions/${id}`, method: 'DELETE' }), invalidatesTags: ['Sessions'] }), activity: builder.query<Envelope<Activity[]>, void>({ query: () => '/auth/login-activity' }), setupMfa: builder.mutation<Envelope<{ secret: string; otpauthUrl: string }>, void>({ query: () => ({ url: '/auth/mfa/setup', method: 'POST' }) }), enableMfa: builder.mutation<Envelope<null>, { code: string }>({ query: body => ({ url: '/auth/mfa/enable', method: 'POST', body }) }),
        employees: builder.query<Envelope<EmployeePage>, void>({ query: () => '/employees', providesTags: ['Employees'] }), employee: builder.query<Envelope<Employee>, string>({ query: id => `/employees/${id}`, providesTags: (_r, _e, id) => [{ type: 'Employees', id }] }), createEmployee: builder.mutation<Envelope<Employee>, Partial<Employee>>({ query: body => ({ url: '/employees', method: 'POST', body }), invalidatesTags: ['Employees'] }), updateEmployee: builder.mutation<Envelope<Employee>, { id: string; body: Partial<Employee> }>({ query: ({ id, body }) => ({ url: `/employees/${id}`, method: 'PUT', body }), invalidatesTags: ['Employees'] }), deleteEmployee: builder.mutation<Envelope<Employee>, string>({ query: id => ({ url: `/employees/${id}`, method: 'DELETE' }), invalidatesTags: ['Employees'] }), restoreEmployee: builder.mutation<Envelope<Employee>, string>({ query: id => ({ url: `/employees/${id}/restore`, method: 'POST' }), invalidatesTags: ['Employees'] })
    })
});
export const { useLoginMutation, useRefreshMutation, useLogoutMutation, useForgotPasswordMutation, useResetPasswordMutation, useVerifyEmailMutation, useChangePasswordMutation, useSessionsQuery, useRevokeSessionMutation, useActivityQuery, useSetupMfaMutation, useEnableMfaMutation, useEmployeesQuery, useEmployeeQuery, useCreateEmployeeMutation, useUpdateEmployeeMutation, useDeleteEmployeeMutation, useRestoreEmployeeMutation } = api;

