import fs from'node:fs';import{EmployeeDocument}from'../models/Document.js';import{Employee}from'../models/Employee.js';import{User}from'../models/User.js';import{AppError}from'../utils/AppError.js';import{sendNotification}from'./notification.service.js';const HR=['SUPER_ADMIN','ORGANIZATION_ADMIN','HR_ADMIN','HR_EXECUTIVE'];
export class DocumentService{
async list(filter:any,user:any){const actor=await this.actor(user),rows=await EmployeeDocument.find({...filter,status:'ACTIVE'}).populate('employeeId','employeeId firstName lastName department email').sort({createdAt:-1}).lean();return rows.filter((x:any)=>this.canAccess(x,actor))}
async create(data:any,file:Express.Multer.File,user:any){if(!file)throw new AppError(422,'Document file is required','FILE_REQUIRED');const actor=await this.actor(user),employee=await this.employeeForUpload(data.employeeId,actor),safe=this.metadata(data);const item=await EmployeeDocument.create({...safe,employeeId:employee._id,organizationId:user.organizationId,currentVersion:1,verificationStatus:'PENDING',approvalStatus:'PENDING',versions:[{version:1,fileName:file.filename,originalName:file.originalname,mimeType:file.mimetype,size:file.size,storagePath:file.path,uploadedBy:user.id}],access:{visibility:'HR',allowEmployee:true,userIds:[user.id]}});await this.notify(user,item.id,'Document uploaded',`${item.title} is pending verification.`,'INFO');return item}
async replace(id:string,file:Express.Multer.File,note:string,user:any){const actor=await this.actor(user),item=await EmployeeDocument.findOne({_id:id,organizationId:user.organizationId,status:'ACTIVE'}).populate('employeeId','email').select('+versions.storagePath');if(!item||!this.canAccess(item,actor))throw new AppError(404,'Document not found','NOT_FOUND');if(!file)throw new AppError(422,'Replacement file is required','FILE_REQUIRED');item.currentVersion+=1;item.versions.push({version:item.currentVersion,fileName:file.filename,originalName:file.originalname,mimeType:file.mimetype,size:file.size,storagePath:file.path,uploadedBy:user.id,changeNote:String(note||'').slice(0,300)});item.verificationStatus='PENDING';item.approvalStatus='PENDING';item.rejectionReason=undefined;await item.save();await this.notify(user,item.id,'Document replaced',`${item.title} is pending verification.`,'INFO');return item}
async file(id:string,version:number|undefined,user:any){const actor=await this.actor(user),item=await EmployeeDocument.findOne({_id:id,organizationId:user.organizationId,status:'ACTIVE'}).populate('employeeId','email').select('+versions.storagePath');if(!item||!this.canAccess(item,actor))throw new AppError(404,'Document not found','NOT_FOUND');const selected=item.versions.find(x=>x.version===(version||item.currentVersion));if(!selected?.storagePath||!fs.existsSync(selected.storagePath))throw new AppError(404,'Document file not found','FILE_NOT_FOUND');return{item,version:selected}}
async review(id:string,data:any,user:any){const item=await EmployeeDocument.findOne({_id:id,organizationId:user.organizationId,status:'ACTIVE'});if(!item)throw new AppError(404,'Document not found','NOT_FOUND');if(!['VERIFIED','REJECTED'].includes(data.verificationStatus))throw new AppError(422,'Choose VERIFIED or REJECTED','INVALID_STATUS');if(data.verificationStatus==='REJECTED'&&!String(data.rejectionReason||'').trim())throw new AppError(422,'A rejection reason is required','REASON_REQUIRED');item.verificationStatus=data.verificationStatus;item.verifiedBy=user.id;item.verifiedAt=new Date();item.rejectionReason=data.verificationStatus==='REJECTED'?String(data.rejectionReason).trim():undefined;await item.save();for(const userId of item.access?.userIds||[])await this.notify({id:userId,organizationId:user.organizationId},item.id,`Document ${data.verificationStatus.toLowerCase()}`,data.verificationStatus==='REJECTED'?`${item.title}: ${item.rejectionReason}`:`${item.title} has been verified.`,data.verificationStatus==='REJECTED'?'WARNING':'SUCCESS');return item}
async requestDelete(id:string,reason:string,user:any){if(!reason.trim())throw new AppError(422,'A deletion reason is required','REASON_REQUIRED');const actor=await this.actor(user),item=await EmployeeDocument.findOne({_id:id,organizationId:user.organizationId,status:'ACTIVE'}).populate('employeeId','email');if(!item||!this.canAccess(item,actor))throw new AppError(404,'Document not found','NOT_FOUND');item.deletionStatus='REQUESTED';item.deletionReason=reason.trim().slice(0,500);item.deletionRequestedBy=user.id;item.deletionRequestedAt=new Date();await item.save();return item}
async remove(id:string,user:any){const item=await EmployeeDocument.findOne({_id:id,organizationId:user.organizationId,status:'ACTIVE'});if(!item)throw new AppError(404,'Document not found','NOT_FOUND');item.status='DELETED';item.deletionStatus='APPROVED';item.deletedAt=new Date();item.deletedBy=user.id;return item.save()}
async reminders(org?:string,days=30){const now=new Date(),to=new Date(Date.now()+days*86400000).toISOString().slice(0,10);const rows=await EmployeeDocument.find({organizationId:org,status:'ACTIVE',expiryDate:{$gte:now.toISOString().slice(0,10),$lte:to}}).populate('employeeId','firstName lastName email');for(const row of rows){row.lastExpiryReminderAt=new Date();await row.save();for(const userId of row.access?.userIds||[])await this.notify({id:userId,organizationId:org},row.id,'Document expiring',`${row.title} expires on ${row.expiryDate}.`,'WARNING')}return rows.map((x:any)=>({documentId:x._id,title:x.title,category:x.category,expiryDate:x.expiryDate,employee:x.employeeId}))}
canAccess(item:any,user:any){if(HR.includes(user.role))return true;const employee=item.employeeId as any;return item.access?.visibility==='ORGANIZATION'||item.access?.userIds?.map(String).includes(String(user.id))||item.access?.roles?.includes(user.role)||(item.access?.allowEmployee&&employee?.email===user.email)}
private async employeeForUpload(requested:any,user:any){if(HR.includes(user.role)&&requested){const found=await Employee.findOne({_id:requested,organizationId:user.organizationId,deletedAt:null});if(found)return found}const own=await Employee.findOne({email:user.email,organizationId:user.organizationId,deletedAt:null});if(!own)throw new AppError(403,'No employee profile is linked to this account','EMPLOYEE_NOT_LINKED');return own}
private async actor(user:any){const account=await User.findOne({_id:user.id,organizationId:user.organizationId,active:true}).select('email').lean();if(!account)throw new AppError(401,'Authenticated user no longer exists','UNAUTHORIZED');return{...user,email:account.email}}
private metadata(data:any){const title=String(data.title||'').trim();if(!title)throw new AppError(422,'Document title is required','TITLE_REQUIRED');const expiryDate=String(data.expiryDate||'').trim();if(expiryDate&&!/^\d{4}-\d{2}-\d{2}$/.test(expiryDate))throw new AppError(422,'Expiry date must use YYYY-MM-DD','INVALID_EXPIRY_DATE');const masked=String(data.maskedDocumentNumber||'').trim();if(masked&&!/^•••• [A-Za-z0-9]{1,4}$/.test(masked))throw new AppError(422,'Only the last four document-number characters may be stored','INVALID_DOCUMENT_NUMBER');return{title:title.slice(0,150),category:String(data.category||''),description:String(data.description||'').trim().slice(0,1000)||undefined,expiryDate:expiryDate||undefined,maskedDocumentNumber:masked||undefined}}
private notify(user:any,id:any,title:string,message:string,severity:string){return sendNotification({userId:String(user.id),organizationId:user.organizationId,event:'DOCUMENT_EXPIRY',title,message,module:'DOCUMENT',recordId:String(id),link:'/documents',severity})}}
