import { EmployeeRepository } from '../repositories/employee.repository.js'; import { Employee,type IEmployee,type EmployeeStatus } from '../models/Employee.js'; import { AppError } from '../utils/AppError.js'; import { encrypt } from '../utils/security.js';
import { EmployeeIdConfig } from '../models/EmployeeIdConfig.js';
const tracked:Record<string,string>={department:'DEPARTMENT_CHANGE',designation:'DESIGNATION_CHANGE',reportingManager:'MANAGER_CHANGE',status:'STATUS_CHANGE',location:'LOCATION_CHANGE'};
export class EmployeeService { constructor(private repo=new EmployeeRepository()){}
  async list(page:number,limit:number,organizationId?:string,query?:Record<string,string>){
    const filter:Record<string,any>={deletedAt:null,...(organizationId?{organizationId}:{})};
    if(query?.search)filter.$or=['firstName','lastName','email','employeeId'].map(key=>({[key]:{$regex:query.search,$options:'i'}}));
    ['department','designation','branch','employeeType','status'].forEach(key=>{if(query?.[key])filter[key]=query[key]});
    if(query?.joiningDateFrom||query?.joiningDateTo)filter.joiningDate={...(query.joiningDateFrom?{$gte:new Date(query.joiningDateFrom)}:{}),...(query.joiningDateTo?{$lte:new Date(query.joiningDateTo)}:{})};
    const [items,total]=await Promise.all([this.repo.list(filter,(page-1)*limit,limit),this.repo.count(filter)]);return{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}}
  async get(id:string,organizationId?:string,includeDeleted=false){const item=await Employee.findById(id).lean();if(!item||(!includeDeleted&&item.deletedAt)||(organizationId&&item.organizationId!==organizationId))throw new AppError(404,'Employee not found','NOT_FOUND');return item}
  async create(input:Record<string,any>){const data=this.secure(input);const duplicate=await Employee.findOne({email:String(data.email).toLowerCase(),...(data.organizationId?{organizationId:data.organizationId}:{})}).select('_id deletedAt').lean();if(duplicate)throw new AppError(409,duplicate.deletedAt?'An archived employee already uses this work email':'An employee with this work email already exists','EMPLOYEE_EMAIL_EXISTS');const roleCode=String(input.roleCode||'EMPLOYEE').toUpperCase();const config=await EmployeeIdConfig.findOneAndUpdate({roleCode,...(data.organizationId?{organizationId:data.organizationId}:{organizationId:{$exists:false}})},{$inc:{nextSequence:1}},{new:false});if(config){const parts=[config.prefix];if(config.includeYear)parts.push(String(new Date().getFullYear()));parts.push(String(config.nextSequence).padStart(config.padding,'0'));data.employeeId=parts.join(config.separator)}else{const year=new Date().getFullYear();const last=await Employee.findOne({employeeId:new RegExp(`^EMP-${year}-\\d{5}$`)}).sort({employeeId:-1}).select('employeeId').lean();const sequence=last?Number(last.employeeId.split('-').pop())+1:1;data.employeeId=`EMP-${year}-${String(sequence).padStart(5,'0')}`}delete data.roleCode;try{return await this.repo.create(data as IEmployee)}catch(error:any){if(error?.code===11000){const field=Object.keys(error.keyPattern??{})[0]??'employee';throw new AppError(409,`An employee with this ${field} already exists`,'EMPLOYEE_CONFLICT')}throw error}}
  async update(id:string,input:Record<string,any>,organizationId?:string,actor?:string){const employee=await this.repo.findById(id);if(!employee||(organizationId&&employee.organizationId!==organizationId))throw new AppError(404,'Employee not found','NOT_FOUND');const data=this.secure(input);for(const [field,type] of Object.entries(tracked)){const before=String((employee as any)[field]??'');const after=data[field];if(after!==undefined&&String(after)!==before)employee.history?.push({type,from:before,to:String(after),effectiveDate:new Date(),changedBy:actor})}Object.assign(employee,data);return employee.save()}
  async remove(id:string,organizationId?:string,actor?:string){const employee=await this.repo.findById(id);if(!employee||employee.deletedAt||(organizationId&&employee.organizationId!==organizationId))throw new AppError(404,'Employee not found','NOT_FOUND');employee.deletedAt=new Date();employee.history?.push({type:'SOFT_DELETE',from:employee.status,to:'DELETED',effectiveDate:new Date(),changedBy:actor});return employee.save()}
  async restore(id:string,organizationId?:string,actor?:string){const employee=await Employee.findOne({_id:id,deletedAt:{$ne:null}});if(!employee||(organizationId&&employee.organizationId!==organizationId))throw new AppError(404,'Deleted employee not found','NOT_FOUND');employee.deletedAt=null;employee.history?.push({type:'RESTORE',from:'DELETED',to:employee.status,effectiveDate:new Date(),changedBy:actor});return employee.save()}
  async history(organizationId?:string,limit=100){const employees=await Employee.find({...organizationId?{organizationId}:{},'history.0':{$exists:true}}).select('employeeId firstName lastName history').lean();return employees.flatMap(employee=>(employee.history??[]).map(event=>({...event,employeeId:employee.employeeId,employeeName:`${employee.firstName} ${employee.lastName}`}))).sort((a,b)=>new Date(b.effectiveDate).getTime()-new Date(a.effectiveDate).getTime()).slice(0,Math.min(limit,500))}
  async importMany(rows:Record<string,any>[],organizationId?:string){if(!Array.isArray(rows)||!rows.length)throw new AppError(422,'At least one employee is required','VALIDATION_ERROR');if(rows.length>500)throw new AppError(422,'A maximum of 500 employees can be imported at once','VALIDATION_ERROR');const created=[],errors=[];for(const [index,row] of rows.entries()){try{created.push(await this.create({...row,organizationId}))}catch(error:any){errors.push({row:index+1,email:row.email,message:error?.message??'Import failed'})}}return{createdCount:created.length,failedCount:errors.length,created,errors}}
  async action(id:string,action:string,value:string|undefined,note:string|undefined,effectiveDate:Date|undefined,organizationId?:string,actor?:string){const employee=await this.repo.findById(id);if(!employee||(organizationId&&employee.organizationId!==organizationId))throw new AppError(404,'Employee not found','NOT_FOUND');const map:Record<string,{field:string,value?:string,type:string}>={ACTIVATE:{field:'status',value:'ACTIVE',type:'STATUS_CHANGE'},DEACTIVATE:{field:'status',value:'INACTIVE',type:'STATUS_CHANGE'},TRANSFER:{field:'location',type:'LOCATION_CHANGE'},PROMOTE:{field:'designation',type:'DESIGNATION_CHANGE'},CHANGE_MANAGER:{field:'reportingManager',type:'MANAGER_CHANGE'},START_RESIGNATION:{field:'status',value:'ON_NOTICE',type:'STATUS_CHANGE'},TERMINATE:{field:'status',value:'TERMINATED',type:'STATUS_CHANGE'},RESTORE:{field:'status',value:'ACTIVE',type:'STATUS_CHANGE'}};const spec=map[action]!;const before=String((employee as any)[spec.field]??'');const after=spec.value??value;if(!after)throw new AppError(422,'Action value is required','VALIDATION_ERROR');(employee as any)[spec.field]=after;employee.history?.push({type:spec.type,from:before,to:after,note,effectiveDate:effectiveDate??new Date(),changedBy:actor});return employee.save()}
  private secure(input:Record<string,any>){const data={...input};if(input.bank){const {accountNumber,routingCode,...safe}=input.bank;data.bank={...safe,...(accountNumber?{accountNumberEncrypted:encrypt(accountNumber)}:{}),...(routingCode?{routingCodeEncrypted:encrypt(routingCode)}:{})}}if(input.statutory)data.statutory=input.statutory.map((item:any)=>({country:item.country,type:item.type,valueEncrypted:encrypt(item.value)}));return data}
  async bulkAction(ids:string[],action:string,value:string,organizationId?:string,actor?:string){
    const update:Record<string,any>={};let historyType:string;
    if(action==='UPDATE_DEPARTMENT'){update.department=value;historyType='DEPARTMENT_CHANGE'}
    else if(action==='UPDATE_MANAGER'){update.reportingManager=value;historyType='MANAGER_CHANGE'}
    else if(action==='ACTIVATE'){update.status='ACTIVE';historyType='STATUS_CHANGE'}
    else if(action==='DEACTIVATE'){update.status='INACTIVE';historyType='STATUS_CHANGE'}
    else throw new AppError(400,'Invalid bulk action','VALIDATION_ERROR');
    const employees=await Employee.find({_id:{$in:ids},...(organizationId?{organizationId}:{})});
    const changedField=Object.keys(update)[0]!;
    const bulkOps=employees.map(e=>({updateOne:{filter:{_id:e._id},update:{$set:update,$push:{history:{type:historyType,from:(e as any)[changedField],to:value,effectiveDate:new Date(),changedBy:actor}}}}}));
    return Employee.bulkWrite(bulkOps as any);
  }
}
