type ExternalState={name:string;state_code?:string};type ExternalCountry={name:string;iso2?:string;iso3?:string;phone_code?:string;states?:ExternalState[]};
const base='https://countriesnow.space/api/v0.1/countries';let cache:{data:ExternalCountry[];expires:number}|undefined;const ttl=86400000;
async function external(path:string,init?:RequestInit){const response=await fetch(`${base}${path}`,init);if(!response.ok)throw new Error('Location provider request failed');const body=await response.json()as{error:boolean;msg?:string;data:any};if(body.error)throw new Error(body.msg||'Location provider request failed');return body.data}
async function geography(){if(cache&&cache.expires>Date.now())return cache.data;const raw=await external('/states');if(!Array.isArray(raw))throw new Error('Location provider returned an invalid country response');const data=raw as ExternalCountry[];cache={data,expires:Date.now()+ttl};return data}const countryId=(c:ExternalCountry)=>c.iso3||c.iso2||c.name;
export async function countries(search=''){const q=search.toLowerCase();return(await geography()).filter(c=>!q||c.name.toLowerCase().includes(q)).map(c=>({id:countryId(c),name:c.name,iso2:c.iso2,iso3:c.iso3,phoneCode:c.phone_code})).sort((a,b)=>a.name.localeCompare(b.name))}
export async function states(id:string,search=''){const country=(await geography()).find(c=>countryId(c)===id);if(!country)return null;const q=search.toLowerCase();return(country.states||[]).filter(s=>!q||s.name.toLowerCase().includes(q)).map(s=>({id:`${id}:${s.state_code||s.name}`,name:s.name,countryId:id})).sort((a,b)=>a.name.localeCompare(b.name))}
export async function cities(stateId:string,search=''){const split=stateId.indexOf(':');if(split<1)return null;const id=stateId.slice(0,split),stateKey=stateId.slice(split+1),country=(await geography()).find(c=>countryId(c)===id),state=country?.states?.find(s=>(s.state_code||s.name)===stateKey);if(!country||!state)return null;const data=await external('/state/cities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({country:country.name,state:state.name})})as string[],q=search.toLowerCase();return[...new Set(data)].filter(name=>!q||name.toLowerCase().includes(q)).map(name=>({id:`${stateId}:${name}`,name,stateId,countryId:id})).sort((a,b)=>a.name.localeCompare(b.name))}
export async function validateLocation(countryName:string,stateName?:string,cityName?:string){const country=(await geography()).find(c=>c.name===countryName);if(!country)return false;if(!stateName)return!(country.states?.length);const state=country.states?.find(s=>s.name===stateName);if(!state)return false;if(!cityName)return true;const values=await external('/state/cities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({country:country.name,state:state.name})})as string[];return values.includes(cityName)}

