import { RoleDefinition } from '../models/RoleDefinition.js'; import { User } from '../models/User.js'; import { roles } from '../constants/roles.js'; import { AppError } from '../utils/AppError.js';
const labels:Record<string,string>={SUPER_ADMIN:'Super Admin',ORGANIZATION_ADMIN:'Organization Admin',HR_ADMIN:'HR Admin',HR_EXECUTIVE:'HR Executive',DEPARTMENT_MANAGER:'Department Manager',TEAM_LEADER:'Team Leader',PAYROLL_MANAGER:'Payroll Manager',RECRUITER:'Recruiter',FINANCE_USER:'Finance User',EMPLOYEE:'Employee'};
export class RoleService{
  async ensure(org?:string){for(const role of roles)await RoleDefinition.findOneAndUpdate({organizationId:org,code:role},{$setOnInsert:{organizationId:org,name:labels[role],code:role,type:'SYSTEM',systemRole:role,priority:role==='SUPER_ADMIN'?1:50,status:'ACTIVE',permissions:role==='SUPER_ADMIN'?['system.manage']:[]}},{upsert:true})}
  async list(org?:string,includeDeleted=false){await this.ensure(org);const filter:any={organizationId:org};if(!includeDeleted)filter.status={$ne:'DELETED'};const rows=await RoleDefinition.find(filter).sort({priority:1,name:1}).lean();return Promise.all(rows.map(async x=>({...x,userCount:await User.countDocuments({organizationId:org,$or:[{customRoleId:String(x._id)},{role:x.systemRole}]}),permissionCount:x.permissions.length})))}
  create(data:any,org?:string,actor?:string){return RoleDefinition.create({...data,organizationId:org,type:'CUSTOM',systemRole:undefined,code:data.code.toUpperCase(),createdBy:actor})}
  async update(id:string,data:any,org?:string){const item=await RoleDefinition.findOne({_id:id,organizationId:org});if(!item)throw new AppError(404,'Role not found','NOT_FOUND');if(item.type==='SYSTEM'){delete data.code;delete data.type;delete data.systemRole}if(data.isDefault)await RoleDefinition.updateMany({organizationId:org,_id:{$ne:id}},{$set:{isDefault:false}});Object.assign(item,data);return item.save()}
  async duplicate(id:string,data:any,org?:string,actor?:string){const source=await RoleDefinition.findOne({_id:id,organizationId:org});if(!source)throw new AppError(404,'Role not found','NOT_FOUND');return this.create({name:data.name||`${source.name} Copy`,code:data.code||`${source.code}_COPY`,description:source.description,permissions:source.permissions,priority:source.priority+1},org,actor)}
  async remove(id:string,org?:string){const item=await RoleDefinition.findOne({_id:id,organizationId:org});if(!item)throw new AppError(404,'Role not found','NOT_FOUND');if(item.type==='SYSTEM')throw new AppError(422,'System roles cannot be deleted','SYSTEM_ROLE_PROTECTED');item.status='DELETED';item.deletedAt=new Date();return item.save()}
  async restore(id:string,org?:string){const item=await RoleDefinition.findOne({_id:id,organizationId:org,type:'CUSTOM'});if(!item)throw new AppError(404,'Custom role not found','NOT_FOUND');item.status='ACTIVE';item.deletedAt=undefined;return item.save()}
  async assign(roleId:string,userIds:string[],org?:string){const role=await RoleDefinition.findOne({_id:roleId,organizationId:org,status:'ACTIVE'});if(!role)throw new AppError(404,'Active role not found','NOT_FOUND');if(role.type==='SYSTEM')await User.updateMany({_id:{$in:userIds},organizationId:org},{$set:{role:role.systemRole},$unset:{customRoleId:1}});else await User.updateMany({_id:{$in:userIds},organizationId:org},{$set:{customRoleId:String(role._id)}});return{assigned:userIds.length}}
}
