import type{NextFunction,Request,Response}from'express';import{DocumentService}from'../services/document.service.js';import{ok}from'../utils/response.js';const service=new DocumentService();const user=(req:Request)=>req.user!;
export async function list(req:Request,res:Response,next:NextFunction){try{const filter:any={organizationId:req.user?.organizationId};if(req.query.employeeId)filter.employeeId=req.query.employeeId;if(req.query.category)filter.category=req.query.category;if(req.query.expiringBefore)filter.expiryDate={$lte:req.query.expiringBefore};ok(res,await service.list(filter,user(req)))}catch(e){next(e)}}
export async function upload(req:Request,res:Response,next:NextFunction){try{ok(res,await service.create(req.body,req.file!,user(req)),'Document uploaded',201)}catch(e){next(e)}}
export async function replace(req:Request,res:Response,next:NextFunction){try{ok(res,await service.replace(String(req.params.id),req.file!,req.body.changeNote,user(req)),'Document replaced')}catch(e){next(e)}}
export async function preview(req:Request,res:Response,next:NextFunction){try{const{version}=await service.file(String(req.params.id),req.query.version?Number(req.query.version):undefined,user(req));res.setHeader('content-type',version.mimeType||'application/octet-stream');res.setHeader('content-disposition',`${req.query.download==='true'?'attachment':'inline'}; filename="${version.originalName}"`);res.sendFile(version.storagePath!)}catch(e){next(e)}}
export async function review(req:Request,res:Response,next:NextFunction){try{ok(res,await service.review(String(req.params.id),req.body,user(req)),'Document reviewed')}catch(e){next(e)}}
export async function requestDelete(req:Request,res:Response,next:NextFunction){try{ok(res,await service.requestDelete(String(req.params.id),String(req.body.reason||''),user(req)),'Document deletion requested')}catch(e){next(e)}}
export async function remove(req:Request,res:Response,next:NextFunction){try{ok(res,await service.remove(String(req.params.id),user(req)),'Document deleted')}catch(e){next(e)}}
export async function reminders(req:Request,res:Response,next:NextFunction){try{ok(res,await service.reminders(req.user?.organizationId,Number(req.body.days)||30),'Expiry reminders processed')}catch(e){next(e)}}
