import type { NextFunction,Request,Response } from 'express'; import { EmployeeService } from '../services/employee.service.js'; import { ok } from '../utils/response.js';
export function prepareEmployeeForm(req:Request,_res:Response,next:NextFunction){try{if(typeof req.body.data==='string'){const data=JSON.parse(req.body.data),types:Record<string,string>={FULL_TIME:'PERMANENT',PART_TIME:'PART_TIME',CONTRACT:'CONTRACT',INTERN:'INTERN',CONSULTANT:'CONSULTANT'};req.body={...data,personalPhone:data.personalPhone??data.phone,currentAddress:data.currentAddress??data.address,employeeType:data.employeeType??types[String(data.employmentType)]??data.employmentType,department:data.department??data.departmentId,designation:data.designation??data.designationId,branch:data.branch??data.branchId,shift:data.shift??data.shiftId,reportingManager:data.reportingManager??data.reportingManagerId,noticePeriod:data.noticePeriod??String(data.noticePeriodDays??'')}}next()}catch(error){next(error)}}
const service=new EmployeeService();
export async function listEmployees(req:Request,res:Response,next:NextFunction){try{ok(res,await service.list(Number(req.query.page)||1,Math.min(Number(req.query.limit)||10,100),req.user?.organizationId,req.query as Record<string,string>))}catch(e){next(e)}}
export async function getEmployee(req:Request,res:Response,next:NextFunction){try{ok(res,await service.get(String(req.params.id),req.user?.organizationId))}catch(e){next(e)}}
export async function createEmployee(req:Request,res:Response,next:NextFunction){try{ok(res,await service.create({...req.body,organizationId:req.user?.organizationId}),'Employee created',201)}catch(e){next(e)}}
export async function updateEmployee(req:Request,res:Response,next:NextFunction){try{ok(res,await service.update(String(req.params.id),req.body,req.user?.organizationId,req.user?.id),'Employee updated')}catch(e){next(e)}}
export async function deleteEmployee(req:Request,res:Response,next:NextFunction){try{ok(res,await service.remove(String(req.params.id),req.user?.organizationId,req.user?.id),'Employee deleted')}catch(e){next(e)}}
export async function restoreEmployee(req:Request,res:Response,next:NextFunction){try{ok(res,await service.restore(String(req.params.id),req.user?.organizationId,req.user?.id),'Employee restored')}catch(e){next(e)}}
export async function employeeHistory(req:Request,res:Response,next:NextFunction){try{ok(res,await service.history(req.user?.organizationId,Number(req.query.limit)||100),'Employee history fetched')}catch(e){next(e)}}
export async function importEmployees(req:Request,res:Response,next:NextFunction){try{ok(res,await service.importMany(req.body.employees,req.user?.organizationId),'Employee import completed',201)}catch(e){next(e)}}
export async function employeeAction(req:Request,res:Response,next:NextFunction){try{const {action,value,note,effectiveDate}=req.body;ok(res,await service.action(String(req.params.id),action,value,note,effectiveDate,req.user?.organizationId,req.user?.id),'Employee action completed')}catch(e){next(e)}}
