import type {NextFunction,Request,Response} from 'express';
import {Announcement} from '../models/Announcement.js';
import {Approval} from '../models/Approval.js';
import {Attendance} from '../models/Attendance.js';
import {EmployeeDocument as Document} from '../models/Document.js';
import {Employee} from '../models/Employee.js';
import {LeaveBalance} from '../models/LeaveBalance.js';
import {LeaveRequest} from '../models/LeaveRequest.js';
import {LeaveType} from '../models/LeaveType.js';
import {Holiday} from '../models/Holiday.js';
import {OrganizationMaster} from '../models/OrganizationMaster.js';
import {PayrollRun} from '../models/Payroll.js';
import {Shift} from '../models/Shift.js';
import {User} from '../models/User.js';
import {AppError} from '../utils/AppError.js';
import {ok} from '../utils/response.js';
const scope=(req:Request)=>req.user?.organizationId?{organizationId:req.user.organizationId}:{};
const paged=<T>(items:T[],page=1,limit=20,total=items.length)=>({items,pagination:{page,limit,total,totalPages:Math.ceil(total/limit),hasNextPage:page*limit<total,hasPreviousPage:page>1}});
async function self(req:Request){const user=await User.findById(req.user?.id).lean();return user?Employee.findOne({...scope(req),email:user.email,deletedAt:null}).lean():null}
export async function options(req:Request,res:Response,next:NextFunction){try{const type=String(req.params.type??req.path.split('/').filter(Boolean)[0]).replace(/s$/,'').toUpperCase();if(type==='SHIFT'){const rows=await Shift.find(scope(req)).sort({name:1}).lean();return ok(res,rows.map(x=>({id:String(x._id),name:x.name,code:x.code})))}const rows=await OrganizationMaster.find({...scope(req),type,status:'ACTIVE'}).sort({name:1}).lean();ok(res,rows.map(x=>({id:String(x._id),name:x.name,code:x.code})))}catch(e){next(e)}}
export async function announcement(req:Request,res:Response,next:NextFunction){try{const item=await Announcement.findOne({_id:req.params.id,...scope(req)}).lean();if(!item)throw new AppError(404,'Announcement not found','NOT_FOUND');ok(res,item)}catch(e){next(e)}}
export async function employeeId(req:Request,res:Response,next:NextFunction){try{const prefix=`EMP${new Date().getFullYear()}`,latest=await Employee.findOne({...scope(req),employeeId:{$regex:`^${prefix}`}}).sort({employeeId:-1}).select('employeeId').lean(),sequence=Number(latest?.employeeId.slice(prefix.length))||0;ok(res,{employeeId:`${prefix}${String(sequence+1).padStart(4,'0')}`})}catch(e){next(e)}}
export async function managers(req:Request,res:Response,next:NextFunction){try{const filter:any={...scope(req),status:'ACTIVE',deletedAt:null};if(req.query.departmentId)filter.department=req.query.departmentId;ok(res,await Employee.find(filter).sort({firstName:1}).lean())}catch(e){next(e)}}
export async function documents(req:Request,res:Response,next:NextFunction){try{ok(res,await Document.find({...scope(req),employeeId:req.params.id}).sort({createdAt:-1}).lean())}catch(e){next(e)}}
export async function history(req:Request,res:Response,next:NextFunction){try{const item=await Employee.findOne({_id:req.params.id,...scope(req)}).select('history').lean();if(!item)throw new AppError(404,'Employee not found','NOT_FOUND');ok(res,item.history??[])}catch(e){next(e)}}
export async function hierarchy(req:Request,res:Response,next:NextFunction){try{const employee=await Employee.findOne({_id:req.params.id,...scope(req)}).lean();if(!employee)throw new AppError(404,'Employee not found','NOT_FOUND');const manager=employee.reportingManager?await Employee.findOne({...scope(req),employeeId:employee.reportingManager}).lean():null,reports=await Employee.find({...scope(req),reportingManager:employee.employeeId,deletedAt:null}).lean();ok(res,{employee,manager,reports})}catch(e){next(e)}}
export async function employeeStatus(req:Request,res:Response,next:NextFunction){try{const status=req.params.action==='activate'?'ACTIVE':'INACTIVE',item=await Employee.findOneAndUpdate({_id:req.params.id,...scope(req)},{$set:{status},$push:{history:{type:status,note:req.body.reason,changedBy:req.user?.id}}},{new:true});if(!item)throw new AppError(404,'Employee not found','NOT_FOUND');ok(res,item)}catch(e){next(e)}}
export async function balance(req:Request,res:Response,next:NextFunction){try{const employee=await self(req);if(!employee)throw new AppError(404,'Employee profile is not linked to this login account','EMPLOYEE_PROFILE_NOT_FOUND');const year=new Date().getFullYear(),org=scope(req);const types=await LeaveType.find({...org,status:'ACTIVE'}).sort({name:1}).lean();if(types.length)await LeaveBalance.bulkWrite(types.map(type=>({updateOne:{filter:{...org,employeeId:employee._id,leaveTypeId:type._id,year},update:{$setOnInsert:{allocated:type.annualAllocation,carriedForward:0,used:0,pending:0,encashed:0}},upsert:true}})));const[rows,holidays]:[any[],any[]]=await Promise.all([LeaveBalance.find({...org,employeeId:employee._id,year}).populate('leaveTypeId','name status').lean(),Holiday.find({...org,date:{$regex:`^${year}`},status:'ACTIVE'}).select('date').lean()]);ok(res,{balances:rows.filter(x=>x.leaveTypeId?.status!=='INACTIVE').map(x=>({leaveTypeId:String(x.leaveTypeId?._id??x.leaveTypeId),leaveTypeName:x.leaveTypeId?.name??'Leave',allocated:x.allocated,used:x.used,pending:x.pending,available:x.allocated+x.carriedForward-x.used-x.pending})),policy:{weekendDays:[0,6],holidays:holidays.map(x=>x.date),requiresHrApproval:false}})}catch(e){next(e)}}
export async function leaves(req:Request,res:Response,next:NextFunction){try{const employee=await self(req),filter:any={...scope(req)};if(req.params.mode==='mine')filter.employeeId=employee?._id??null;if(req.params.mode==='pending')filter.status={$in:['PENDING','MANAGER_APPROVED','HR_APPROVED']};const page=Number(req.query.page)||1,limit=Math.min(Number(req.query.limit)||20,100),[items,total]=await Promise.all([LeaveRequest.find(filter).populate('employeeId','firstName lastName employeeId').populate('leaveTypeId','name').sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),LeaveRequest.countDocuments(filter)]);ok(res,paged(items,page,limit,total))}catch(e){next(e)}}
export async function leave(req:Request,res:Response,next:NextFunction){try{const item=await LeaveRequest.findOne({_id:req.params.id,...scope(req)}).populate('employeeId','firstName lastName employeeId').populate('leaveTypeId','name').lean();if(!item)throw new AppError(404,'Leave request not found','NOT_FOUND');ok(res,item)}catch(e){next(e)}}
export async function months(req:Request,res:Response,next:NextFunction){try{const rows:any[]=await PayrollRun.find(scope(req)).sort({month:-1}).lean();ok(res,paged(rows.map(x=>({...x,id:String(x._id),period:x.month,employeeCount:x.totals?.employeeCount??x.items?.length??0,processedCount:x.items?.length??0,failedCount:0,totalAmount:x.totals?.totalNet??0,currency:'INR',pendingApprovals:['DRAFT','PROCESSING','REVIEW_PENDING'].includes(x.status)?1:0,publishedPayslips:x.items?.filter((i:any)=>i.payslipPublished).length??0,salaryRevisionRequests:0,finalSettlementAmount:0}))))}catch(e){next(e)}}
export async function payrollEmployees(req:Request,res:Response,next:NextFunction){try{const run:any=req.query.payrollId?await PayrollRun.findOne({_id:req.query.payrollId,...scope(req)}).lean():await PayrollRun.findOne(scope(req)).sort({month:-1}).lean();ok(res,paged((run?.items??[]).map((x:any)=>({id:String(x._id),employeeId:x.employeeCode,employeeName:x.employeeName,department:x.department,grossSalary:x.grossSalary,totalDeduction:x.totalDeductions,netSalary:x.netSalary,status:run.status}))))}catch(e){next(e)}}
export async function dashboard(req:Request,res:Response,next:NextFunction){try{const org=scope(req),today=new Date().toISOString().slice(0,10),month=today.slice(0,7);if(req.params.kind==='hr'){const[totalEmployees,activeEmployees,presentToday,pendingApprovals,expiringDocuments]=await Promise.all([Employee.countDocuments({...org,deletedAt:null}),Employee.countDocuments({...org,status:'ACTIVE',deletedAt:null}),Attendance.countDocuments({...org,date:today,status:{$in:['PRESENT','LATE','WORK_FROM_HOME','ON_DUTY']}}),Approval.countDocuments({...org,status:'PENDING'}),Document.countDocuments({...org,expiryDate:{$lte:new Date(Date.now()+2592000000)}})]);return ok(res,{totalEmployees,activeEmployees,newJoiners:0,onProbation:0,presentToday,absentToday:Math.max(activeEmployees-presentToday,0),onLeave:0,pendingOnboarding:0,expiringDocuments,pendingApprovals,departmentDistribution:[],attendanceTrend:[]})}if(req.params.kind==='payroll'){const run:any=await PayrollRun.findOne({...org,month}).lean();return ok(res,{payrollMonth:month,processingStatus:run?.status??'NOT_STARTED',totalPayrollAmount:run?.totals?.totalNet??0,currency:'INR',pendingApprovals:run&&!['PUBLISHED','PAID'].includes(run.status)?1:0,publishedPayslips:run?.items?.filter((x:any)=>x.payslipPublished).length??0,failedRecords:0,salaryRevisionRequests:0,processingProgress:run?.status==='PUBLISHED'?100:run?50:0})}if(req.params.kind==='manager')return ok(res,{teamMemberCount:0,present:0,absent:0,onLeave:0,late:0,pendingApprovals:await Approval.countDocuments({...org,status:'PENDING'}),taskStatus:[],leaveCalendar:[],birthdays:[],performance:[]});ok(res,{attendance:{status:'NOT_STARTED',nextAction:'CHECK_IN',shiftStart:'',shiftEnd:'',workedMinutes:0,requiredMinutes:480},leaveBalance:0,holidays:[],tasks:[],announcements:[],celebrations:[],quickActions:[]})}catch(e){next(e)}}
