import type{NextFunction,Request,Response}from'express';import{OffboardingService}from'../services/offboarding.service.js';import{Employee}from'../models/Employee.js';import{User}from'../models/User.js';import{PdfService}from'../services/pdf.service.js';import{AppError}from'../utils/AppError.js';import{ok}from'../utils/response.js';const service=new OffboardingService(),actor=(req:Request)=>req.user!;
export async function list(req:Request,res:Response,next:NextFunction){try{ok(res,await service.list(req.user?.organizationId,actor(req)))}catch(e){next(e)}}
export async function get(req:Request,res:Response,next:NextFunction){try{ok(res,await service.get(String(req.params.id),req.user?.organizationId,actor(req)))}catch(e){next(e)}}
export async function request(req:Request,res:Response,next:NextFunction){try{ok(res,await service.request(req.body,req.file,req.user?.organizationId,actor(req)),'Resignation requested',201)}catch(e){next(e)}}
export async function action(req:Request,res:Response,next:NextFunction){try{const item:any=await service.action(String(req.params.id),req.body.action,req.body.data||{},req.user?.organizationId,actor(req));if(item.status==='NOTICE_PERIOD')await Employee.findByIdAndUpdate(item.employeeId._id||item.employeeId,{$set:{status:'ON_NOTICE'}});if(item.status==='COMPLETED'){const employee=await Employee.findById(item.employeeId._id||item.employeeId).select('email');if(employee)await User.updateOne({email:employee.email,organizationId:req.user?.organizationId},{$set:{active:false}})}ok(res,item,'Offboarding updated')}catch(e){next(e)}}
export async function task(req:Request,res:Response,next:NextFunction){try{ok(res,await service.task(String(req.params.id),String(req.params.taskId),req.body,req.user?.organizationId,actor(req)),'Clearance task updated')}catch(e){next(e)}}
export async function settlement(req:Request,res:Response,next:NextFunction){try{ok(res,await service.settlement(String(req.params.id),req.body,req.user?.organizationId,actor(req)),'Final settlement saved')}catch(e){next(e)}}
export async function exitInterview(req:Request,res:Response,next:NextFunction){try{ok(res,await service.exitInterview(String(req.params.id),req.body,req.user?.organizationId,actor(req)),'Exit interview updated')}catch(e){next(e)}}
export async function attachment(req:Request,res:Response,next:NextFunction){try{const item:any=await service.get(String(req.params.id),req.user?.organizationId,actor(req),true),file=item.resignation?.documentUrl;if(!file)throw new AppError(404,'Attachment not found','NOT_FOUND');res.setHeader('content-type',item.resignation.attachmentMimeType||'application/octet-stream');res.setHeader('content-disposition',`attachment; filename="${item.resignation.attachmentName||'resignation-attachment'}"`);res.sendFile(file)}catch(e){next(e)}}
export async function letter(req:Request,res:Response,next:NextFunction){try{const item:any=await service.get(String(req.params.id),req.user?.organizationId,actor(req)),employee:any=item.employeeId,type=req.params.type==='experience'?'Experience Letter':'Relieving Letter';if(item.status!=='COMPLETED')throw new AppError(409,'Letter is available after exit completion','EXIT_INCOMPLETE');const pdf=await new PdfService().render('letter',{companyName:'EmployeeHub',companyAddress:'Organization address',month:type,employeeName:`${employee.firstName} ${employee.lastName}`,employeeCode:employee.employeeId,department:employee.department,bankName:'',bankAccountMasked:'',earnings:[],deductions:[],grossSalary:0,totalDeductions:0,netSalary:0,amountInWords:`This is to certify that ${employee.firstName} ${employee.lastName} served as ${employee.designation}. Last working date: ${item.resignation.proposedLastWorkingDate}.`});if(!item.letters)item.letters={};if(req.params.type==='experience')item.letters.experienceGeneratedAt=new Date();else item.letters.relievingGeneratedAt=new Date();await item.save();res.setHeader('content-type','application/pdf');res.setHeader('content-disposition',`attachment; filename=${req.params.type}-letter-${employee.employeeId}.pdf`);res.send(pdf)}catch(e){next(e)}}
