import { Router } from 'express';
import { authenticate } from '../middleware/authenticate.js';
import { requirePermission } from '../middleware/authorize.js';
import { attendanceSelfieUpload } from '../middleware/upload.js';
import * as c from '../controllers/attendance.controller.js';
import { PERMISSIONS } from '../constants/permissions.js';

export const attendanceRoutes = Router();
attendanceRoutes.use(authenticate);
attendanceRoutes.get('/me', c.mine);
attendanceRoutes.get('/today', c.today);
attendanceRoutes.get('/monthly-report', requirePermission(PERMISSIONS['attendance.view']), c.monthlyReport);
attendanceRoutes.get('/monthly-summary', requirePermission(PERMISSIONS['attendance.view']), c.monthlySummary);
attendanceRoutes.get('/', requirePermission(PERMISSIONS['attendance.view']), c.list);
attendanceRoutes.post('/check-in', attendanceSelfieUpload, c.prepareMobileAttendance, c.checkIn);
attendanceRoutes.post('/:id/events/:event', attendanceSelfieUpload, c.prepareMobileAttendance, c.event);
attendanceRoutes.get('/summary/monthly', requirePermission(PERMISSIONS['attendance.view']), c.summary);
attendanceRoutes.post('/corrections', c.correction);
attendanceRoutes.get('/corrections/all', requirePermission(PERMISSIONS['attendance.manage']), c.corrections);
attendanceRoutes.get('/rules/current', requirePermission(PERMISSIONS['attendance.view']), c.getRules);
const hr = requirePermission(PERMISSIONS['attendance.manage']);
attendanceRoutes.get('/office-locations', requirePermission(PERMISSIONS['attendance.view']), c.officeLocations);
attendanceRoutes.post('/validate-location', c.validateLocation);
attendanceRoutes.get('/verification-logs', hr, c.verificationLogs);
attendanceRoutes.get('/:attendanceId/notifications', c.notifications);
attendanceRoutes.get('/:attendanceId', c.detail);
attendanceRoutes.post('/:attendanceId/overtime/:action', hr, c.overtime);
attendanceRoutes.post('/office-locations', hr, c.createOfficeLocation);
attendanceRoutes.patch('/office-locations/:id', hr, c.updateOfficeLocation);
attendanceRoutes.delete('/office-locations/:id', hr, c.deleteOfficeLocation);
attendanceRoutes.post('/manual', hr, c.manual);
attendanceRoutes.post('/bulk', hr, c.bulk);
attendanceRoutes.patch('/corrections/:id/review', hr, c.review);
attendanceRoutes.put('/rules/current', requirePermission(PERMISSIONS['attendance.manage']), c.saveRules);
