import{Router}from'express';import{authenticate}from'../middleware/authenticate.js';import{requirePermission}from'../middleware/authorize.js';import{PERMISSIONS}from'../constants/permissions.js';import*as c from'../controllers/mobile-compat.controller.js';import*as m from'../controllers/master-compat.controller.js';import*as p from'../controllers/payroll-compat.controller.js';
export const mobileCompatRoutes=Router();mobileCompatRoutes.use(authenticate);const employeeView=requirePermission(PERMISSIONS['employee.view']),employeeManage=requirePermission(PERMISSIONS['employee.update']),masterManage=requirePermission(PERMISSIONS['master.manage']),leaveView=requirePermission(PERMISSIONS['leave.view']),payrollView=requirePermission(PERMISSIONS['payroll.view']);const setParam=(name:string,value:string,handler:any)=>(req:any,res:any,next:any)=>{req.params[name]=value;return handler(req,res,next)};
mobileCompatRoutes.get('/dashboard/:kind',c.dashboard);
mobileCompatRoutes.get(['/branches/options','/departments/options','/designations/options','/shifts/options'],employeeView,c.options);
mobileCompatRoutes.get(['/departments','/designations'],masterManage,m.list);mobileCompatRoutes.post(['/departments','/designations'],masterManage,m.save);mobileCompatRoutes.get(['/departments/:id','/designations/:id'],masterManage,m.get);mobileCompatRoutes.patch(['/departments/:id','/designations/:id'],masterManage,m.save);mobileCompatRoutes.delete(['/departments/:id','/designations/:id'],masterManage,m.remove);
mobileCompatRoutes.get('/announcements/:id',c.announcement);
mobileCompatRoutes.post('/employees/generate-id',employeeManage,c.employeeId);mobileCompatRoutes.get('/employees/managers',employeeView,c.managers);mobileCompatRoutes.get('/employees/:id/documents',employeeView,c.documents);mobileCompatRoutes.get('/employees/:id/employment-history',employeeView,c.history);mobileCompatRoutes.get('/employees/:id/hierarchy',employeeView,c.hierarchy);mobileCompatRoutes.post('/employees/:id/activate',employeeManage,setParam('action','activate',c.employeeStatus));mobileCompatRoutes.post('/employees/:id/deactivate',employeeManage,setParam('action','deactivate',c.employeeStatus));
mobileCompatRoutes.get('/leaves/balance',leaveView,c.balance);mobileCompatRoutes.get('/leaves/my-requests',leaveView,setParam('mode','mine',c.leaves));mobileCompatRoutes.get('/leaves/pending-approvals',requirePermission(PERMISSIONS['leave.approve']),setParam('mode','pending',c.leaves));mobileCompatRoutes.get('/leaves/:id',leaveView,c.leave);
mobileCompatRoutes.get('/payroll/payslips',payrollView,p.list);mobileCompatRoutes.get('/payroll/payslips/:id/download',payrollView,p.download);mobileCompatRoutes.get('/payroll/payslips/:id',payrollView,p.get);mobileCompatRoutes.get('/payroll/summary',payrollView,p.summary);mobileCompatRoutes.get('/payroll/months',payrollView,c.months);mobileCompatRoutes.get('/payroll/employees',payrollView,c.payrollEmployees);mobileCompatRoutes.patch('/payroll/:id/approve',requirePermission(PERMISSIONS['payroll.approve']),setParam('action','approve',p.transition));mobileCompatRoutes.post('/payroll/:id/publish',requirePermission(PERMISSIONS['payroll.publish']),setParam('action','publish',p.transition));
