import { useEffect, useState } from 'react';
import { ArrowLeft, Eye, Loader2, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

type Preview = { subject:string; text:string; html:string };
type PreviewSet = { customer:Preview; superAdmin:Preview };
const token=()=>localStorage.getItem('token')||sessionStorage.getItem('token')||'';

export function DemoEmailPreviews(){
  const[templates,setTemplates]=useState<PreviewSet>();const[error,setError]=useState('');
  useEffect(()=>{const base=import.meta.env.VITE_API_BASE_URL||'/api/v1';fetch(`${base}/admin/demo-requests/email-previews`,{headers:{authorization:`Bearer ${token()}`}}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message||'Unable to load previews');if(!body.data?.sampleOnly)throw new Error('Preview safety marker is missing');setTemplates(body.data.templates)}).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load previews'))},[]);
  return <div className="mx-auto max-w-[1500px]"><Link to="/super-admin/demo-requests" className="inline-flex items-center gap-2 text-sm font-bold text-brand"><ArrowLeft size={16}/>Demo requests</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-brand">Visual review</p><h1 className="text-2xl font-bold">Demo request email previews</h1><p className="mt-1 text-sm text-slate-500">Review-only renderings of the customer confirmation and Super Admin notification.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><ShieldCheck size={18}/>Sample data only · sending disabled</div></div>{error&&<p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{!templates&&!error?<div className="grid h-72 place-items-center"><Loader2 className="animate-spin text-brand"/></div>:templates&&<div className="mt-6 grid gap-6 xl:grid-cols-2"><PreviewCard label="Customer Demo Confirmation" preview={templates.customer}/><PreviewCard label="Super Admin New Demo Request" preview={templates.superAdmin}/></div>}</div>;
}

function PreviewCard({label,preview}:{label:string;preview:Preview}){const[mode,setMode]=useState<'desktop'|'mobile'>('desktop');return <section className="card min-w-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-bold"><Eye size={17}/>{label}</div><p className="mt-2 text-xs text-slate-500">Subject</p><p className="text-sm font-semibold">{preview.subject}</p></div><div className="flex rounded-lg border p-1"><button className={`rounded-md px-2 py-1 text-xs font-bold ${mode==='desktop'?'bg-indigo-100 text-indigo-800':''}`} onClick={()=>setMode('desktop')}>Desktop</button><button className={`rounded-md px-2 py-1 text-xs font-bold ${mode==='mobile'?'bg-indigo-100 text-indigo-800':''}`} onClick={()=>setMode('mobile')}>Mobile</button></div></div><div className="mt-4 overflow-x-auto rounded-xl bg-slate-200 p-3"><iframe title={`${label} sample preview`} sandbox="" srcDoc={preview.html} className="mx-auto block h-[720px] rounded-lg border-0 bg-white transition-all" style={{width:mode==='mobile'?375:'100%',maxWidth:'100%'}}/></div><details className="mt-4 rounded-xl border p-3"><summary className="cursor-pointer text-sm font-bold">Plain-text fallback</summary><pre className="mt-3 whitespace-pre-wrap text-xs leading-5 text-slate-500">{preview.text}</pre></details></section>}
