import { Building2, CalendarClock, ClipboardCheck, Contact, LayoutGrid, Mail, MessageCircle, Phone, Video } from 'lucide-react';
export const lists={jobTitle:['Founder / Owner','CEO / Director','HR Manager','HR Executive','Operations Manager','IT Manager','Payroll Manager','Team Lead','Other'],industry:['Information Technology','Software Development','Manufacturing','Healthcare','Education','Retail','Finance','Banking','Real Estate','Construction','Hospitality','Logistics','Consulting','Government','Non-Profit','Other'],companySize:['1–10 employees','11–50 employees','51–100 employees','101–250 employees','251–500 employees','501–1,000 employees','More than 1,000 employees'],currentHRMethod:['Spreadsheets','Paper or manual process','Existing HRMS software','Accounting software','Custom internal software','No current system','Other'],preferredDemoTime:['9:00 AM – 11:00 AM','11:00 AM – 1:00 PM','2:00 PM – 4:00 PM','4:00 PM – 6:00 PM','Flexible'],preferredContactMethod:['Phone call','Email','Google Meet','Microsoft Teams','WhatsApp']};
export const modules=['Employee Management','Attendance Management','Leave Management','Payroll and Payslips','Recruitment','Employee Onboarding','Task Management','Performance Management','Expense Management','Asset Management','Documents','Reports and Analytics','Mobile Application','Roles and Permissions'];
export const steps=[
 {id:'contact',label:'Contact',title:'Tell us about yourself',description:'Provide your contact information so our product specialist can reach you.',panel:'Let’s start with your contact details.',icon:Contact,fields:['fullName','workEmail','phoneCountryCode','phoneNumber','jobTitle','customJobTitle']},
 {id:'company',label:'Company',title:'Tell us about your company',description:'This helps us personalize the demo for your organization.',panel:'Help us understand your organization.',icon:Building2,fields:['companyName','companyWebsite','industry','customIndustry','companySize','country','state','city']},
 {id:'requirements',label:'Requirements',title:'What are you looking for?',description:'Select the modules and HR challenges relevant to your organization.',panel:'Choose the features that matter to your team.',icon:LayoutGrid,fields:['interestedModules','currentHRMethod','additionalRequirements']},
 {id:'schedule',label:'Schedule',title:'Choose your preferred demo schedule',description:'Select a convenient date, time, and contact method.',panel:'Select a convenient time for your personalized walkthrough.',icon:CalendarClock,fields:['preferredDemoDate','preferredDemoTime','preferredTimezone','preferredContactMethod']},
 {id:'review',label:'Review',title:'Review your demo request',description:'Confirm your information before submitting the request.',panel:'Review your details and confirm your request.',icon:ClipboardCheck,fields:['contactConsent','marketingConsent']}
];
export const contactIcons={'Phone call':Phone,Email:Mail,'Google Meet':Video,'Microsoft Teams':Video,WhatsApp:MessageCircle};
