/**
 * Permission constants and role-to-permissions mapping for RBAC.
 */
import type { Role } from './roles.js';

export const PERMISSIONS = {
  'employee.view': 'employee.view',
  'employee.create': 'employee.create',
  'employee.update': 'employee.update',
  'employee.update_own': 'employee.update_own',
  'employee.delete': 'employee.delete',
  'employee.export': 'employee.export',
  'employee.import': 'employee.import',
  'attendance.view': 'attendance.view',
  'attendance.manage': 'attendance.manage',
  'attendance.mark': 'attendance.mark',
  'leave.view': 'leave.view',
  'leave.apply': 'leave.apply',
  'leave.approve': 'leave.approve',
  'leave.recommend': 'leave.recommend',
  'leave.manage': 'leave.manage',
  'payroll.view': 'payroll.view',
  'payroll.generate': 'payroll.generate',
  'payroll.approve': 'payroll.approve',
  'payroll.publish': 'payroll.publish',
  'performance.view': 'performance.view',
  'performance.review': 'performance.review',
  'performance.self_review': 'performance.self_review',
  'recruitment.view': 'recruitment.view',
  'recruitment.manage': 'recruitment.manage',
  'asset.view': 'asset.view',
  'asset.manage': 'asset.manage',
  'report.view': 'report.view',
  'report.export': 'report.export',
  'settings.view': 'settings.view',
  'settings.manage': 'settings.manage',
  'role.view': 'role.view',
  'role.manage': 'role.manage',
  'subscription.view': 'subscription.view',
  'subscription.manage': 'subscription.manage',
  'plan.view': 'plan.view',
  'plan.manage': 'plan.manage',
  'announcement.view': 'announcement.view',
  'announcement.manage': 'announcement.manage',
  'expense.view': 'expense.view',
  'expense.approve': 'expense.approve',
  'expense.submit': 'expense.submit',
  'reimbursement.view': 'reimbursement.view',
  'reimbursement.approve': 'reimbursement.approve',
  'payroll.settings': 'payroll.settings',
  'audit.view': 'audit.view',
  'document.view': 'document.view',
  'document.manage': 'document.manage',
  'holiday.view': 'holiday.view',
  'holiday.manage': 'holiday.manage',
  'shift.view': 'shift.view',
  'shift.manage': 'shift.manage',
  'onboarding.view': 'onboarding.view',
  'onboarding.manage': 'onboarding.manage',
  'offboarding.view': 'offboarding.view',
  'offboarding.manage': 'offboarding.manage',
  'organization.view': 'organization.view',
  'organization.manage': 'organization.manage',
  'organization.create': 'organization.create',
  'organization.suspend': 'organization.suspend',
  'organization.delete': 'organization.delete',
  'user.view_all': 'user.view_all',
  'system_report.view': 'system_report.view',
  'global_settings.manage': 'global_settings.manage',
  'master.manage': 'master.manage',
  'task.view': 'task.view',
  'task.manage': 'task.manage'
  ,'approval.view':'approval.view'
  ,'approval.action':'approval.action'
  ,'demo-request.view':'demo-request.view'
  ,'demo-request.update':'demo-request.update'
  ,'demo-request.assign':'demo-request.assign'
  ,'demo-request.schedule':'demo-request.schedule'
  ,'demo-request.contact':'demo-request.contact'
  ,'demo-request.email.retry':'demo-request.email.retry'
  ,'demo-request.export':'demo-request.export'
  ,'demo-request.archive':'demo-request.archive'
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const rolePermissions: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ORGANIZATION_ADMIN: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['employee.create'],
    PERMISSIONS['employee.update'],
    PERMISSIONS['employee.delete'],
    PERMISSIONS['employee.export'],
    PERMISSIONS['employee.import'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['attendance.manage'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.apply'],
    PERMISSIONS['leave.approve'],
    PERMISSIONS['leave.manage'],
    PERMISSIONS['payroll.view'],
    PERMISSIONS['payroll.generate'],
    PERMISSIONS['payroll.approve'],
    PERMISSIONS['payroll.publish'],
    PERMISSIONS['payroll.settings'],
    PERMISSIONS['performance.view'],
    PERMISSIONS['performance.review'],
    PERMISSIONS['recruitment.view'],
    PERMISSIONS['recruitment.manage'],
    PERMISSIONS['asset.view'],
    PERMISSIONS['asset.manage'],
    PERMISSIONS['report.view'],
    PERMISSIONS['report.export'],
    PERMISSIONS['settings.view'],
    PERMISSIONS['settings.manage'],
    PERMISSIONS['role.view'],
    PERMISSIONS['role.manage'],
    PERMISSIONS['announcement.view'],
    PERMISSIONS['announcement.manage'],
    PERMISSIONS['document.view'],
    PERMISSIONS['document.manage'],
    PERMISSIONS['holiday.view'],
    PERMISSIONS['holiday.manage'],
    PERMISSIONS['shift.view'],
    PERMISSIONS['shift.manage'],
    PERMISSIONS['onboarding.view'],
    PERMISSIONS['onboarding.manage'],
    PERMISSIONS['offboarding.view'],
    PERMISSIONS['offboarding.manage'],
    PERMISSIONS['organization.view'],
    PERMISSIONS['organization.manage'],
    PERMISSIONS['master.manage'],
    PERMISSIONS['task.view'],
    PERMISSIONS['task.manage']
  ],
  HR_ADMIN: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['employee.create'],
    PERMISSIONS['employee.update'],
    PERMISSIONS['employee.delete'],
    PERMISSIONS['employee.export'],
    PERMISSIONS['employee.import'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['attendance.manage'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.apply'],
    PERMISSIONS['leave.approve'],
    PERMISSIONS['leave.manage'],
    PERMISSIONS['performance.view'],
    PERMISSIONS['performance.review'],
    PERMISSIONS['recruitment.view'],
    PERMISSIONS['recruitment.manage'],
    PERMISSIONS['asset.view'],
    PERMISSIONS['asset.manage'],
    PERMISSIONS['report.view'],
    PERMISSIONS['report.export'],
    PERMISSIONS['announcement.view'],
    PERMISSIONS['announcement.manage'],
    PERMISSIONS['document.view'],
    PERMISSIONS['document.manage'],
    PERMISSIONS['holiday.view'],
    PERMISSIONS['holiday.manage'],
    PERMISSIONS['shift.view'],
    PERMISSIONS['shift.manage'],
    PERMISSIONS['onboarding.view'],
    PERMISSIONS['onboarding.manage'],
    PERMISSIONS['offboarding.view'],
    PERMISSIONS['offboarding.manage'],
    PERMISSIONS['settings.view']
  ],
  HR_EXECUTIVE: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['employee.create'],
    PERMISSIONS['employee.update'],
    PERMISSIONS['employee.export'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.apply'],
    PERMISSIONS['leave.approve'],
    PERMISSIONS['recruitment.view'],
    PERMISSIONS['recruitment.manage'],
    PERMISSIONS['document.view'],
    PERMISSIONS['document.manage'],
    PERMISSIONS['onboarding.view'],
    PERMISSIONS['onboarding.manage'],
    PERMISSIONS['performance.view']
  ],
  DEPARTMENT_MANAGER: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.approve'],
    PERMISSIONS['performance.view'],
    PERMISSIONS['performance.review'],
    PERMISSIONS['task.view'],
    PERMISSIONS['task.manage'],
    PERMISSIONS['report.view'],
    PERMISSIONS['holiday.view'],
    PERMISSIONS['shift.view']
  ],
  TEAM_LEADER: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.recommend'],
    PERMISSIONS['performance.view'],
    PERMISSIONS['performance.review'],
    PERMISSIONS['task.view'],
    PERMISSIONS['task.manage'],
    PERMISSIONS['holiday.view'],
    PERMISSIONS['shift.view']
  ],
  PAYROLL_MANAGER: [
    PERMISSIONS['payroll.view'],
    PERMISSIONS['payroll.generate'],
    PERMISSIONS['payroll.approve'],
    PERMISSIONS['payroll.publish'],
    PERMISSIONS['payroll.settings'],
    PERMISSIONS['report.view'],
    PERMISSIONS['report.export']
  ],
  RECRUITER: [
    PERMISSIONS['recruitment.view'],
    PERMISSIONS['recruitment.manage'],
    PERMISSIONS['employee.view'],
    PERMISSIONS['document.view']
  ],
  EMPLOYEE: [
    PERMISSIONS['employee.view'],
    PERMISSIONS['employee.update_own'],
    PERMISSIONS['attendance.view'],
    PERMISSIONS['attendance.mark'],
    PERMISSIONS['leave.view'],
    PERMISSIONS['leave.apply'],
    PERMISSIONS['holiday.view'],
    PERMISSIONS['payroll.view'],
    PERMISSIONS['document.view'],
    PERMISSIONS['asset.view'],
    PERMISSIONS['task.view'],
    PERMISSIONS['performance.view'],
    PERMISSIONS['performance.self_review'],
    PERMISSIONS['expense.submit'],
    PERMISSIONS['announcement.view']
  ],
  IT_ADMIN: [PERMISSIONS['employee.view'],PERMISSIONS['asset.view'],PERMISSIONS['asset.manage'],PERMISSIONS['offboarding.view']],
  FINANCE_USER: [
    PERMISSIONS['payroll.view'],
    PERMISSIONS['report.view'],
    PERMISSIONS['report.export'],
    PERMISSIONS['expense.view'],
    PERMISSIONS['expense.approve'],
    PERMISSIONS['reimbursement.view'],
    PERMISSIONS['reimbursement.approve']
  ]
};

for(const role of ['ORGANIZATION_ADMIN','HR_ADMIN','HR_EXECUTIVE','DEPARTMENT_MANAGER','TEAM_LEADER','PAYROLL_MANAGER','FINANCE_USER'] as Role[]){rolePermissions[role].push(PERMISSIONS['approval.view'],PERMISSIONS['approval.action'])}
for(const role of ['EMPLOYEE','DEPARTMENT_MANAGER','TEAM_LEADER','PAYROLL_MANAGER','FINANCE_USER'] as Role[]){rolePermissions[role].push(PERMISSIONS['offboarding.view'])}
rolePermissions.PAYROLL_MANAGER.push(PERMISSIONS['offboarding.manage']);

export function permissionsForRole(role: Role) {
  return rolePermissions[role] || [];
}
